### ISSUE TITLE
Review onPaste event on TextInput

### ISSUE THREAD

**Issue by TheSavior** [Microsoft/reactxp#1017]
There is a PR on React Native core adding an onPaste prop to listen to clipboard paste events for TextInput. Specifically to get access to images that are pasted into the text input.

It would be great to get your team’s eyes on it to make sure it is being designed in a way that will work across platforms. 

https://github.com/facebook/react-native/pull/22794

**Comment by berickson1** [comment]
On web, the API is pretty simple. The onPaste handler provides an array of pasted items, each of which is a DataTransferItem as per the spec: https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem

Effectively, it has a 'kind' (file or string) and type (mime type) property and then async getters (getFile and getString).

On the RN side, you may want to consider passing a reference to the object pasted instead of the full object - it could cause memory pressure (& possibly crashes) if the user pasted a large object that needed to be serialized, sent across the bridge and loaded into the JS runtime (where it may possibly just be ignored, depending on consumption)

**Comment by TheSavior** [comment]
Thanks for taking a look! Can you share your feedback on the PR so the original author sees it?
