### ISSUE TITLE
Shorthand style properties should follow CSS rules for precedence

### ISSUE THREAD

**Issue by aschultz** [Microsoft/reactxp#1026]
When combining an array of styles [A, B], ReactXP currently applies a simple merge by copying all properties from B on top of A. For most properties, this works as expected, with values from B overriding values from A.

However, for shorthand properties like margin and padding, this results in unexpected behavior.
<pre>
let A = { marginLeft: 5 };
let B = { margin: 0 };
let C = { marginLeft: 1 };
let D = combine( A, B ); // { marginLeft: 5, margin: 0 }. Should be { margin: 0 }
let E = combine( A, B, C ); // { marginLeft: 1, margin: 0 }. Should be { marginLeft: 1, marginTop: 0, marginBottom: 0, marginRight: 0 }
</pre>

D and E have both properties. When applied to components for web, they get turned into CSS styles and the order of the properties affects the final layout (the later property taking precedence). If "marginLeft" is ordered second,  D will behave as if A overrode B. If "margin" is ordered second, E will behave as if B took precedence over C.

This is strange behavior and likely not what a developer wants. When I specify "margin: 0" in style B, I'm making an explicit request to apply that to all sides. If I wanted to only override a single side, I would do so.  Instead, I get a style that may or may not apply to all sides, depending on what is in style A and what order the properties got copied. This weirdness is called out in ReactXP with console warnings of "Conflicting rules for margin specified".

In CSS, shorthand properties are equivalent to specifying all of the individual properties. Thus setting "margin: 0px" (like B) should override all four sides, regardless of whether a "margin-left" (A) was previously set. https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties. ReactXP should do the same.

**Comment by erictraut** [comment]
We considered doing this, but it would require either much more complex merge logic (which will impose an appreciable runtime overhead) or expansion of all properties (which also imposes a big runtime overhead — especially on RN where all of the extra style text needs to be marshaled across the RN bridge). Since it's an edge case that's easy to avoid programmatically, we decided on a compromise — code that detects the case and warns the developer if ReactXP is running in development mode. When it's running in production mode, these extra checks (and associated assertions) are skipped.

**Comment by aschultz** [comment]
Could you elaborate on how it's an edge case we can easily avoid?

My team has a large number of React components with default styles applied, but allow users of those components to override. If a component uses marginLeft/marginTop/etc and a caller specifies "margin", its a conflict. If a default uses "margin" and a user specifies "marginLeft", its a conflict.

We could require not using shorthand at all, but that's hard to enforce and annoying in practice.

**Comment by erictraut** [comment]
We also have a large number of React components in Skype that allow style overrides. We occasionally hit this problem, but it was rare in practice. When it occurred, we almost immediately noticed the problem because of the assertion, and it was trivial to fix.

I'll also point out that the style merge behaviors in ReactXP were copied from RN. It also doesn't provide a form of smart merging for attributes like "margin" and "marginLeft". (At least, it didn't at the time; it's possible they've added it recently.)

To be clear, I'm not that religious about this issue. I could be convinced that the extra runtime overhead involved in doing a more sophisticated merge is worthwhile. I'm just saying that this was never a significant problem for us, whereas performance was always a big concern.

**Comment by necolas** [comment]
FYI the provided example is not correct about how React Native resolves styles:

```
let A = { marginLeft: 5 };
let B = { margin: 0 };
let D = combine( A, B );
// { marginLeft: 5, margin: 0 }.
// Should be { margin: 0 }
```

The expected result is

```
{ marginLeft: 5, marginTop: 0, marginBottom: 0, marginRight: 0 }
```

https://github.com/necolas/react-native-web/blob/0.10.0/docs/guides/style.md#how-styles-are-resolved

**Comment by erictraut** [comment]
Oh, that's interesting. It looks like RN at some point implemented a smart merge for styles. IIRC, earlier versions of RN didn't do this. We assumed we'd need to add this logic into ReactXP if we wanted the behavior. 

I therefore think it makes sense for us to incorporate that same merge logic in ReactXP's web implementation. We're not as performance-constrained on the web, so I'm not as concerned about perf impact there.

If someone wants to take a crack at writing that logic, a contribution would be welcome. A small test case in RXPTest and an update to the docs will also be necessary.

**Comment by necolas** [comment]
React Native has always resolved styles this way.

> We're not as performance-constrained on the web

Why is this?

**Comment by erictraut** [comment]
The biggest performance constraints are on mobile devices — especially on Android. Web-based ReactXP apps tend to run on desktop devices with more computing cycles available.

**Comment by aschultz** [comment]
So, correct me if I'm wrong, but we have three models?

1. CSS. Expand shorthand and apply precedence by order.
2. ReactNative. Expand shorthand and apply precedence by precision.
3. ReactXP. Don't expand shorthand. Precedence is unpredictable.

I'd argue that 1 is easier to work with than 2, but either is superior to 3.

**Comment by erictraut** [comment]
The philosophy behind ReactXP is to present the same well-defined behavior between RN and ReactJS where possible. Unifying behavior with CSS is a non-goal, so I wouldn't include that in the list.

I think we have two options that are consistent with the ReactXP philosophy:
1. Combining attributes like margin and marginLeft in a style list is documented as a programming error and should be avoided if you want your program to work. In debug mode, an assertion alerts the programmer of this error. (This is the current behavior in ReactXP.)
2. Remove the limitation and update the web implementation of ReactXP to match the behavior of RN. Update the documentation and tests accordingly.

I'm fine with either approach. As I said above, this has never been a big issue for us in practice. I'm supportive of a change to option 2. If you feel strongly about it, a code contribution would be welcome.

**Comment by erictraut** [comment]
I checked in a fix. It will be in the next published version.
