### ISSUE TITLE
Web app incompatible with IE

### ISSUE THREAD

**Issue by psegalen** [Microsoft/reactxp#113]
Hello,
When I try to open my web app with Internet Explorer 11 on my Windows 7 PC, it doesn't show anything.
Opening the console shows a syntax error in the JS bundle: it doesn't seem to support the "class" keyword.
Is there a polyfill or a babel / webpack loader to make the app functional on IE?
Thanks!
Pierre

**Comment by erictraut** [comment]
I just tried to repro this behavior using the hello-world sample, and I'm not seeing the problem. I'm guessing that you've configured TypeScript, Babel or some other tool to emit es6 rather than es5. 

Refer to the [tsconfig file](https://github.com/Microsoft/reactxp/blob/master/samples/hello-world/tsconfig.json) in the hello-world sample for reference.

**Comment by psegalen** [comment]
Thanks, the "target" field of tsconfig.json was set to "es6".
Now it crashes when I use fetch, I guess the polyfill is only included in Chrome, I'll try to install it.

**Comment by psegalen** [comment]
Using https://github.com/github/fetch could be a workaround but unfortunately IE doesn't support Promise either...
This method works: https://medium.com/the-missing-bit/using-promise-and-fetch-with-typescript-8bceca5ae8ed ... but IE also doesn't support Object.assign() ...
![Why???](http://www.meme-generator.org/templates/desperate-got-answer.jpg)

**Comment by psegalen** [comment]
Wow! Good to know: using spread operator instead of Object.assign() is correctly transpiled in es5!
