### ISSUE TITLE
Reactxp with threejs example?

### ISSUE THREAD

**Issue by GolfredoPerezFernandez** [microsoft/reactxp#1161]
HI, i was trying to implement reactxp with threejs but i dont know how to do it... anyone have any example? Thanks.

**Comment by berickson1** [comment]
I've personally never used threejs but with a little searching it looks like something like react-three-fiber (https://github.com/react-spring/react-three-fiber) may do what you want.

In general keep in mind that whatever you use will need support/implementation for the platforms you're targeting.  This can be done either by picking a package that already has support for all the platforms, or by building your own extension that encapsulates multiple different implementations (see https://microsoft.github.io/reactxp/docs/extensions.html)

**Comment by fbartho** [comment]
It's not entirely clear to me why we need an example of how to integrate react-three-fiber with reactxp. I think you can just use them together right? In which case, no extension is needed?

Since this ticket was opened a year ago, I'm going to close it, but please do reply back if this is necessary or valuable and somebody wants to implement it!
