### ISSUE TITLE
zeit now deploy issue

### ISSUE THREAD

**Issue by GolfredoPerezFernandez** [microsoft/reactxp#1180]
Hi im using TodoList example but every work perfectly on localhost i go to http://localhost:8080/todo and works fine..

but after deploy to zeit now and i go to  https://web.example.now.sh/todos i get:
404: NOT_FOUND
Code: RESOURCE_NOT_FOUND
ID: chs1:2c2cc-1579579079524-3b79b18b6667

**Comment by GolfredoPerezFernandez** [comment]
hello?? help with this or is normal?

**Comment by deregtd** [comment]
Sorry, none of us even know what zeit is. :(

In theory if the routing is the same between the two systems all should work.  Can you get anything other than 404s at any url on your zeit deploy?

**Comment by GolfredoPerezFernandez** [comment]
this is zeit now https://zeit.co/ which deployment platform  do you prefer?

**Comment by deregtd** [comment]
The todolist example comes with its own little node server for static hosting, which is usually what I base my simple node deployments off.  Are you trying to use the node server on zeit, or straight static content?  If straight static content, then I have no idea -- the todolist sample should be straightforward enough since it's just the html file and a js file.

**Comment by GolfredoPerezFernandez** [comment]
im trying to use todolist app into a hosting server for live deploy

**Comment by deregtd** [comment]
You need to make sure the hosting server is using nodeserver.js as the application that it's running.

**Comment by GolfredoPerezFernandez** [comment]
ok... i do not know how to do that..
