### ISSUE TITLE
audio support

### ISSUE THREAD

**Issue by sickinga** [Microsoft/reactxp#136]
is there any feature to play local audio files and/or network streamed ones?

**Comment by erictraut** [comment]
Not currently. We have written an internal ReactXP extension that does this, but we haven't open-sourced this code yet. Doing so is a bit complicated because the code is in several internal Skype repos, and it requires some work to disentangle it. It's on my to-do list, but I can't give you a specific timeline. In the meantime, you could use one of several react native audio playback libraries that are published on npm. We ended up writing our own because none of the open-sourced libraries provided us all of the control we required in the Skype client.
