### ISSUE TITLE
Drawer component?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#137]
In the docs, I didn't come across a drawer component (especially for mobile), but neither does react-native itself, and we can either implement a 3rd party drawer package to handle that in react-native, or use react-navigation with react native which comes with a drawer navigator out of the box.

Regarding react-navigation, is it still on the radar for implementation any time soon? I am wondering what the best approach would be at this point, if it is coming out soon, wait for it to be the standard navigation solution in reactxp, or implement a 3rd party drawer (I assume it's possible to integrate a 3rd party drawer in reactxp)?

What are your thoughts on the integration?

**Comment by erictraut** [comment]
We have no plans to include support for a drawer into the ReactXP core. It wouldn't really fit in with the priorities of the library. We're including only those primitive controls that are useful to most apps on both native and web platforms. 

It's likely that we'll be taking a dependency on react-navigation, but we'd expose only the stack-based navigation functionality through ReactXP.

Do you need a drawer control for the web as well, or just RN? Depending on the answer to that question, I think you have a few choices:
1. If you need the control only for native but not the web, you can use one of the third-party drawer packages (including react-navigation).
2. If you need the control for both native and web, it should be pretty straightforward to implement using the other primitive controls in ReactXP.

**Comment by MovingGifts** [comment]
I have the drawer running in native now, but now that the web platform is on the horizon, I think I'll be proceeding with ReactXP; at least giving it a shot and seeing if I come across any short comings and report them along the way, hopefully it's smooth sailing though :)

I am trying to implement the drawer on both platforms (native and web) at this point. I am after the drawer which opens/closes from the left on the hamburger icon toggle, which pushes the visible panel content to the right on open, and reverses on close (as opposed to an overlaying drawer). How do you recommend I do that with ReactXP?

**Comment by erictraut** [comment]
I recommend using two panels that are siblings in the view hierarchy - one for the drawer and the other for the content panel. A translateX transform can then be used to move the drawer to the left of the content panel. You can use the onLayout event to determine the width of the panel, and therefore the initial value of the translateX value.

When the user taps on the hamburger button, use the RX.Animated APIs to animate the translateX value, smoothly moving the drawer into view and at the same time moving the associated content panel to the right. It's important to animate using transforms rather than left/right style attributes because transforms don't require RN (or the browser) to invoke the layout engine at each stage of the animation. That means it's much cheaper, and the animation will be much smoother.

We've used the same approach to implement similar controls within the new Skype client. For example, I implemented the virtualized media viewer control, which allows the user to swipe through an arbitrary collection of photos or videos (and pinch/zoom photos and dismiss the viewer by swiping down). This is all done using transform (and scale) animations and the RX.GestureView to capture gesture events.

Let me know if you get stuck, and I can help you through it.

**Comment by MovingGifts** [comment]
Thank you for your guidance @erictraut 
So I gave it a shot and ended up with screen cap below; here is the text from the screen cap since it may be too quick to read the issues I've encountered in it (probably my implementation is the issue):

1. This content panel has red background that should fill screen, but does not even with `flex: 1` on container
2. This in turn affects the drawer height to not fill the entire available viewport height
3. My animation does not seem to be smooth in both directions, especially on the first click

![reactxp-drawer](https://user-images.githubusercontent.com/1202909/27259558-76fdd716-53e3-11e7-882d-9a4038373010.gif)

Here are the relevant files:
[MainPanel.js](https://gist.github.com/MovingGifts/21ca5e66658e53d43c377937cb00399d)
[DrawerPanel.js](https://gist.github.com/MovingGifts/b7544e10323949d829fc232cf062738c)

I am new to `Animated` and the integration of the drawer, so your help is really appreciated :)

**Comment by erictraut** [comment]
Good progress!

A few tips and suggestions:
1. You're not using the RX.Styles methods to create the style types (e.g. RX.Styles.createViewStyle), so this code may not work cross-platform. The RX.Styles methods perform some transforms on the style to unify the behavior across RN and web.

2. The reason the content panel doesn't fill the screen is that you are missing a "flex: 1" in the second nested RX.View within the MainPanel render function. You included a "flex: 1" in the first RX.View but not the second. The default value for flex is "0". But I'm going to recommend using a different approach here...

3. Rather than use flex: 1 for your content and drawer panels, I recommend using position: 'absolute' and setting the top/bottom/left/right to 0. This will superimpose the panels on top of each other and ensure that they take up the entire available space.

4. The code conditionally renders the drawer. You should always render it, even if it's offscreen at the moment. This is why you're seeing the animation glitching the first time the drawer is opened.

Here's an updated [gist](https://gist.github.com/erictraut/d76393a4f3131e9ef62cc2c22ad6c251).

I've slightly restructured the code to create a more generalized DrawerControl that could be reused. To make it more general, I added props that allow the caller to render the contents of the container and the drawer. I also added the necessary logic to measure the width of the container and update the animated values appropriately. And I added a second animation for the content panel and started it in parallel with the drawer animation.

BTW, I also switched it to TypeScript because I find that I'm just so much more productive when I have syntax corrections in the editor, auto completion, etc. Feel free to ignore the type information if you want to stick with raw JavaScript.

Let me know if you have any follow-up questions.

**Comment by MovingGifts** [comment]
@erictraut Thank you for your tips, suggestions, and refactoring!

I think I missed something since there seems to be extra white space when the drawer opens on both native and web (but much more on web), instead of having just the drawer width without any white space.

![reactxp-drawer-2](https://user-images.githubusercontent.com/1202909/27263904-d9d7f372-5441-11e7-9e28-23ff4e2f43e1.gif)

How can we fix that?

**Comment by erictraut** [comment]
It looks like you still have a "width: 100" attribute on your drawer. In my changes, I removed this so the drawer takes up the entire width of the container (minus the contentPeekAmount).

**Comment by MovingGifts** [comment]
You're right! :)

I overlooked the `width: 100` and now it looks like your code, where the white space is now all green (the drawer). But the drawer is _supposed_ to be a fixed `width: 100` on any platfrom, as opposed to filling all the way to the `contentPeekAmount` I don't think I need `contentPeekAmount` to be 100 in my case. Not sure if I should even have that value, since a drawer of 100px should just push the content over from the left with 100px (when drawer is shown).

I've been playing around with the `drawerControl` to achieve that but still having a hard time :(

**Comment by erictraut** [comment]
I assumed you wanted the "peek" amount to be constant and the visible drawer width to be variable (based on the container width). It's easy to flip that around and make the drawer width constant.

Here's an updated [gist](https://gist.github.com/erictraut/2915c5c045f37704d6ee0436bd97b7bb).

**Comment by MovingGifts** [comment]
Thank you so much for your help :) Works like a charm on both native and web!

ReactXP looks very promising & since I am in the process of converting my current RN app to web, I may be opening up roadblock issues I face during the process, which I am certain will benefit others on their journey from React Native to ReactXP.

I wish I can give you a 🥇 for your support!

**Comment by waheed25** [comment]
is it possible to overlap the red page with drawer ?At this moment when drawer is appears it push the whole screen to the right i want to set background screen static when drawer is open

**Comment by erictraut** [comment]
Sure, just modify the code to remove the content animation. In other words, leave the content where it is, and leave the drawer animation in place.

**Comment by waheed25** [comment]
yes...thanks drawer is working fine.
There is an issue when i reloads my page it shows little jerk of drawer it should be completely hide until i press the button and after jerk it works fine
