### ISSUE TITLE
How to handle routing/navigation on web url and native deeplink?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#138]
So here is a fairly common scenario:

User X receives an email with the following link:
`example.com/:universityName/courses/:course/ratings`

They access their email from an X Platform (web/mobile) device. Let's take the mobile route, since it will include both use cases.

User taps on the link in their email, which opens the URL in their mobile browser. How can we:
 1. Load the correct page from the url in the browser?
 2. Detect user has app or not to show download app/view in app?
 3. When app downloaded or viewed in app is selected:
     a. Navigate to correct view of ratings
     b. Navigate backwards from ratings (landing location), when hitting the back button from there, to go back to the respective previous route (ratings -> :course -> courses -> :universityName -> app root)

I know it's a pretty involved question, but this is a common implementation for apps running both web/mobile and since ReactXP covers development for both, I figured this is the right place to ask :)

**Comment by MovingGifts** [comment]
@erictraut Sorry, to write back so soon, but this is actually the reason I was moving to ReactXP. If this cannot be done at the moment, please just get back to me and let me know.

This will mean I'll have to create a completely separate React website from my React Native app, but since time is of the essence, I would have to do that if I cannot handle the store/view reuse ReactXP offers.

**Comment by erictraut** [comment]
What you're asking about is largely beyond the scope of ReactXP. ReactXP does provide runtime support (on native platforms) for deep link invocation. You can read about it [here](https://microsoft.github.io/reactxp/docs/apis/linking.html). It provides an event called deepLinkRequestEvent that is triggered when a user taps on a link that your app has registered for. But your scenario requires much more than this.

Deep linking and protocol handler registration differs a bit from one platform to the next. Modern app platforms (including iOS, Android and Windows UWP) require protocol handlers to be registered in a declarative manner within the app package. You will need to familiarize yourself with how that works in each case and make the appropriate changes in your app's manifest.

Similar to deep link support, each platform offers different options for forwarding the user to the corresponding app store to download apps that are not installed locally. This needs to be done by the OS because it would be a big security hole if your website's code could determine which apps are installed on the device. I don't personally have much experience with this, but perhaps other folks will respond with advice.

**Comment by MovingGifts** [comment]
Thanks for your quick response Eric, regarding the manifest registration for iOS/Android, that is covered [here](https://medium.com/react-native-training/deep-linking-your-react-native-app-d87c39a1ad5e) for react-navigation.

But for web, when I navigate between multiple panels in ReactXP, the url is always `index.html`, and I was wondering if there is a way where the actual url path with parameters as in the link in the example above can be used when you navigate around the web app.

**Comment by erictraut** [comment]
On the web, you'll need to explicitly set the URL in response to navigation within the app. This is straightforward - just call window.history.pushState with the deep link URL corresponding to the new navigation location. 

For more details, check out [this post](https://github.com/Microsoft/reactxp/issues/120) and the navigation section of [this blog article](https://microsoft.github.io/reactxp/blog/2017/04/27/building-skype-on-reactxp.html).

**Comment by MovingGifts** [comment]
Thank you Eric, I'll look into those :)
