### ISSUE TITLE
Hello World sample slow on android

### ISSUE THREAD

**Issue by Fulanko** [Microsoft/reactxp#140]
When running the 'Hello World' sample on Android phones, it takes around 5 seconds to load the second panel (with the video and svg animation). During that time the app is frozen in the main panel.

Tested on One Plus 3t and Nexus 4

On iOS and Web, the second panel opens instantly after pressing the button.

**Comment by erictraut** [comment]
Yes, this appears to be due to the video player component. The sample app uses the "reactxp-video" plugin, which relies in turn on the open-source "react-native-video" module for iOS and Android. The Android implementation of react-native-video appears to have a long loading time for some videos. If you remove the RXVideo component from the second panel, you'll notice that the problem disappears. If you require video for your Android app and this problem proves to be a blocker, I recommend that you reach out to the authors of "react-native-video" or dig into that code yourself to see if you can diagnose it.

**Comment by Fulanko** [comment]
Thanks,

Here is a quick fix to prevent the app from freezing while the video is loading:
https://github.com/react-native-community/react-native-video/issues/577
