### ISSUE TITLE
How does this differ from react-native-web?

### ISSUE THREAD

**Issue by talarari** [Microsoft/reactxp#15]
https://github.com/necolas/react-native-web

Was this considered and rejected for some reason?

**Comment by spoeck** [comment]
The Answer is on their web page: https://microsoft.github.io/reactxp/docs/faq.html

> How does ReactXP differ from React Native for Web?
React Native for Web is an open-sourced library developed by engineers at Twitter. We started implementing ReactXP before React Native for Web was available.
>
> The goals behind these two efforts are similar, but the approaches differ. ReactXP is a layer that sits on top of React Native and React, whereas React Native for Web is a parallel implementation of React Native — a sibling to React Native for iOS and Android.
>
> ReactXP generally exposes only those props, style attributes, and APIs that are available across all platforms. If you write to ReactXP’s abstraction, you can have high confidence that it will run on all supported platforms in the same manner. The same can be achieved with React Native for Web/iOS/Android, but you need to be more careful about which components, props, and APIs you use.
>
> One of our goals in writing ReactXP was to enable developers to write and debug code in whatever platform environment they felt most comfortable while having confidence that the resulting code would run the same on other platforms.

**Comment by rohmanhm** [comment]
https://github.com/Microsoft/reactxp/issues/7#issuecomment-292767056

**Comment by talarari** [comment]
Sorry , must have missed that part.
Thanks

**Comment by loganpowell** [comment]
Why don't you guys join forces with @necolas and react-native-web? You guys shouldn't be racing. You're both aimed at the same goal and if you both worked together, I believe all those right now who are 'waiting to see who the winner is' or are otherwise on the fence due to the fragmentation in the community would jump on board! I sure would!

**Comment by erictraut** [comment]
We (the Skype team) started developing ReactXP before React Native Web was available. If it had been available at the time, we probably would have contributed to it rather than writing our own from scratch.

It's worth noting that the goals of ReactXP and React Native Web are somewhat different, as reflected in their respective names. React Native Web set out to create a RN implementation for the web that is a peer to the iOS and Android versions. ReactXP set out to create a cross-platform abstraction that unifies (to the extent possible) the interface across these three platforms — and eventually Windows and Mac as well. It purposely excludes many platform-specific features.

At this point, we've built a large source base on top of ReactXP, and we have no desire or motivation to move to another solution. It would be a huge amount of work for us with little or no gain.

**Comment by necolas** [comment]
I'd rather have called React Native for Web something like "React Web" but that package name was taken. The idea was to make the platform agnostic parts of RN work on the web too, and fill in the gaps elsewhere. And RNW was made to support both mobile and desktop web UIs.

Until we get something like React Platform going to target multiple platforms with the "best of" the RN API, RNW adds error-avoiding shims for broader RN compatibility via aliasing. It wasn't something I intended but it became necessary given the situation.

I like ReactXP's inbuilt focus management. There are still things we can learn from all the different projects in this space without having to collapse them all together :)

**Comment by erictraut** [comment]
> There are still things we can learn from all the different projects in this space without having to collapse them all together :)
Great point. I definitely agree.

**Comment by loganpowell** [comment]
> It would be a huge amount of work for us with little or no gain. 
There would be a *huge* gain. Namely, instead of 6K stars and 60 contributors each, you could double those numbers by joining forces. 

I know I'm just a little guy here, but don't you think I have a point? There's much anxiety among people (like myself) in this space about which of your projects to choose. I love what both of you guys are doing - sincerely - we need this kind of thinking (cross-platform solutions).

I suppose the question is: Do your goals differ so much that you would rather have the community (which it seems thinks of them as competitors in the same space) split in two? I mean, there are well-known evangelists putting you guys as competitors in their talks ([for example](https://youtu.be/HLWM2uhv2wI?t=8m45s)). 

@necolas would you consider React-Native-Web to be a super-set of ReactXP? Couldn't you guys work together on the parts that overlap?

I apologize if I come off as disrespectful or ignorant. I say all this with the greatest respect. I am just banging my head about which one to choose and I know others are as well... search your issues (or if you're into Star Wars, your feelings).

**Comment by erictraut** [comment]
Like @necolas said, the two projects can work together by continuing to learn from each other. I think you're asking for something more though. You're asking for a merger of the two projects. That doesn't sound feasible to me because the projects have incompatible interfaces and different implementations. Lots of software has already been built on top of the two libraries.

Even small breaking changes to the ReactXP interface are painful for the Skype team because we've built over 300K lines of app code on top of the library. There's very little incentive for us to replace ReactXP with another implementation — and even less incentive to switch to a new interface. I'm guessing that Nicholas (or at least Twitter) would say the same of React Native for Web.

**Comment by dominicfallows** [comment]
I'd just like to thank @necolas @erictraut and @loganpowell for the recent part of this conversation. I am also in a position of proposing the cross-platform React library for multiple projects. The answers and conversation give me confidence in both equally. I can move forward to look at each individual library and how their respective implementations would work for each project.

**Comment by dominicfallows** [comment]
@necolas to further my proposals, do you know of any React Native for Web projects written in TypeScript?
