### ISSUE TITLE
-webkit-overflow-scrolling: touch

### ISSUE THREAD

**Issue by pixare40** [Microsoft/reactxp#159]
If i want to set this style to smooth the scrolling on Safari, how do I do it?

**Comment by erictraut** [comment]
There's currently no way to set that property in ReactXP's ScrollView. 

Out of curiosity, where would you see this being useful? Wouldn't this apply only to iOS devices? And if so, why wouldn't you use native controls rather than rendering it into HTML?

Incidentally, the [webkit documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling) discourages use of this property for web-facing production apps.

**Comment by pixare40** [comment]
I was trying to improve performance on Mobile Safari but VirtualListView dealt well with the list.
