### ISSUE TITLE
Support deployment to app stores/web?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#162]
Just thinking... expanding `ReactXP` to include the deployment of a `ReactXP` app to all platforms would be a game changer. Almost all apps built will have to deploy to their target platform at one point or another.

Thoughts?

**Comment by erictraut** [comment]
I'm not sure what you have in mind when you say "deployment". Are you talking about the process of submitting the app for review and approval within the iOS App Store and the Google Play Store? For the web version, are you referring to publishing the site's files and configuration to the service that's hosting the site (IIS, Apache, etc.)?

**Comment by RohitLuthra19** [comment]
I think @MovingGifts is looking for this kind of feature https://facebook.github.io/react-native/docs/signed-apk-android.html. Suppose for Android we need to follow above steps. I think this process will be same for ReactXP as well. Because these steps needs to be done at platform specific native code.

**Comment by RohitLuthra19** [comment]
I think @MovingGifts is looking for this kind of feature https://facebook.github.io/react-native/docs/signed-apk-android.html. Suppose for Android we need to follow above steps. I think this process will be same for ReactXP as well. Because these steps needs to be done at platform specific native code. Or may be he is asking about continuous deployment to platform using code push or anything else.

**Comment by MovingGifts** [comment]
@erictraut @RohitLuthra19 Yup, exactly that so what I have in mind is:

1. Getting a locally developed `ReactXP` app into the hands/screens of users via app stores and publishing the files to a url so it can be live and accessible.
2. Maintaining the `ReactXP` app via code push.

In short, to streamline the process of having a `ReactXP` app production ready, live, and updateable.

**Comment by erictraut** [comment]
I don't think this is feasible given the large variety of deployment mechanisms across the various platforms. In any event, I don't think it's the job of a cross-platform UI library like ReactXP to solve this problem. Definitely outside the scope.
