### ISSUE TITLE
Electron not supported

### ISSUE THREAD

**Issue by psegalen** [Microsoft/reactxp#167]
Hi all,

I'm currently trying to create an Electron version of my ReactXP app (deployment target: a Windows 7 compliant app) and I have a `ReferenceError: window is not defined` thrown by the import of `~/reactxp/dist/web/App.js`.
I use webpack to bundle my app, so it's executed via an `eval()` command from inside the bundle.
The problem seems to be caused by this line: https://github.com/Microsoft/reactxp/blob/master/src/web/App.ts#L47

I do want to contribute but I'm wondering about the best way to deal with this issue: should I try to declare an empty global object named `window` or should I try to track every usage of this global object which doesn't exist within Electron as it runs a Node.js server to eliminate those one by one?
I think choosing the second way is much cleaner but I wonder if I'm not going to break things in the process, thinking of the line of code above, I don't know how this is used accross the whole lib!

Any thought?

**Comment by erictraut** [comment]
Although we use Electron, we didn't notice this because we stub out "window". I don't recall why this particular debug variable was added. I suspect it's vestigial and can safely be removed. @deregtd or @berickson1, do you happen to recall? 

I think one of you added src/web/window.ts at some point to address problems like this. Maybe src/web/App.ts should just import this module so it doesn't reference an undefined "window" variable on Electron. Thoughts?

**Comment by ms-deregtd** [comment]
I think you can nuke that one safely.  Should be vestigial.

**Comment by erictraut** [comment]
@psegalen if you delete that line from App.ts, does it then work for you? Just wondering if you'll hit other issues with "window" not being declared.

**Comment by psegalen** [comment]
Yup, it fixes it!
I'll submit a PR.

**Comment by psegalen** [comment]
Submitted PR: https://github.com/Microsoft/reactxp/pull/170
