### ISSUE TITLE
VirtualListView vs .map for web?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#177]
In certain views, I am using `FlatList` for mobile (since it has a few extra props not available in `VirtualListView`).

For those views web counter parts, is it better for performance to use the `VirtualListView` over a normal `.map` to render the items?

Note: I am asking since my api data does not come back with a `key` field as required by `VirtualListView` which means I would have to iterate over each data item, extract a unique value, put that as the `key` field value, before passing it to the `VirtualListView`; where as with `.map`, I can iterate over the data to render and assign the `key` value automatically, without modifying the data items array.

**Comment by erictraut** [comment]
Rendering them directly is simpler and potentially faster if the number of items is relatively small (at most two screens of data). If the data is longer, you really need to use a virtualized view of some sort. Otherwise you'll end up bloating the DOM and consuming significant memory.

Transforming the data list into a set of virtual list item descriptors with keys is very inexpensive compared to a rendering operation, so I wouldn't worry about that.

**Comment by MovingGifts** [comment]
Got it! Thanks for the quick response :)
