### ISSUE TITLE
React Native 0.43

### ISSUE THREAD

**Issue by unindented** [Microsoft/reactxp#18]
What's the plan to keep this project in sync with latest React and React Native? I see it's quite a bit behind `react` (`^15.3.1-rc.2` vs `15.5.3`), `react-native` (`^0.34.0` vs `0.43.2`) and even `react-native-windows` (`^0.33.0` vs `0.43.0-rc.0`).

My fear is that, by adopting this project, I'll be way behind on the latest features of all those projects, as you won't be able to keep it up-to-date.

**Comment by erictraut** [comment]
We will be updating the project and sample code to use React 15.5 and RN 0.42 or 0.43 shortly. After that, we plan to update the project at roughly the same cadence as React Native (about once a month). We fell behind because our main app relies on some changes to RN that have not yet been incorporated into the main RN repo. 

Here's a link to the page where we discuss our versioning strategy.
https://microsoft.github.io/reactxp/versions/version_history.html

**Comment by erictraut** [comment]
@unindented I just updated the project to use React 15.5.3 and React Native 0.42.3. I figured I'd run into a bunch of issues with the upgrade, but it turned out to be straightforward.

**Comment by unindented** [comment]
Wow, nice! Thanks for your responsiveness, and for this super interesting project!
