### ISSUE TITLE
Unit Test Support (Enzyme, Jest, react test renderer) 

### ISSUE THREAD

**Issue by vip-git** [Microsoft/reactxp#187]
Hi,

I was walking through examples on reactxp and found it pretty interesting. Although did not find unit testing that straight forward in terms of migrating react-native code to reactxp.

Any suggestions on what would be the best practise when unit testing react-native apps using react-xp ?

Thanks,
Vipin

**Comment by erictraut** [comment]
In the Skype team, we use Jest for our unit tests. However, we don't tend to write any unit tests for UI components because 1) we try to keep them relatively simple (keeping complex logic in our stores and services), 2) it is difficult to programmatically verify visual and gestural behaviors, and 3) they tend to change frequently (e.g. due to app-wide style changes). For these reasons, we don't find that unit tests are worth it for components.

We do write unit tests for our stores, services, and utility modules. We run these tests locally on dev machines and on our automated build server. They're triggered every time a developer pushes code (either on a private branch or to the master branch). Failures are reported via a Skype channel and/or by email.

If you have already created a testing methodology and infrastructure for React Native, it should readily apply to ReactXP as well.

**Comment by vip-git** [comment]
Hi @erictraut,

We have more of similar setup the only difference is we get updates on slack instead on skype. We also have code linting and over the air analysis of our pull request and every time a pull request is created we show a working demo automatically on appetize. 

We also unit test / component test using enzyme and jest for react native projects. This week and next i will try and see how i can get this integrated with reactxp as i find the concept very interesting. I might have to use react-test-renderer which is what we use for our reactjs projects compared to react native where enzyme is our preference. 

On top of this we also use calabash for End to End testing using cucumber thats something which we would want to integrate with reactxp as well. Possibly with testcafe for reactjs. 

I will try to push a working demo on one of the sample projects which i have forked integrating a sample unit test setup and end to end test. 

You can probably give us feedback if our approach is good enough and scalable in future with reactxp's roadmap ?

Thanks,
Vipin

**Comment by erictraut** [comment]
Sounds interesting. Thanks for sharing!

**Comment by umairfarooq44** [comment]
Hi @vip-git
I am trying to do unit tests using jest and enzyme but I am getting error:
Invariant Violation: _registerComponent(...): Target container is not a DOM element.
which is due to 
RX.UserInterface.setMainView() function of reactxp .
If you could share a repo of unit tests in reactxp, it would be great

**Comment by mfrachet** [comment]
Any more information concerning this issue ? I m quite interested to use enzyme with React XP :D

**Comment by erictraut** [comment]
Closing this issue because it looks like there's nothing new to add.
