### ISSUE TITLE
Expo on reactxp?

### ISSUE THREAD

**Issue by vinils** [Microsoft/reactxp#208]
Hey guys, I would like to know if is it possible to integrate reactxp with expo, if any one has ever made that or if is it on the plans?

I´m an enthusiastic of the reactxp idea and i think expo has some cool stuff which make those things easier and could help people to get into this reactxp community faster, maybe some cools components could appear with that, less bugs and others.

I´m facing some issues to make that and would like to know if it fits on the philosophy of reactxp? if someone has any tip or shortcut for me?

**Comment by erictraut** [comment]
The Skype team (which created ReactXP) doesn't have any plans to integrate with Expo, but it looks like it should be feasible to do so. After all, ReactXP builds directly on top of React Native. You wouldn't be able to use any of the Expo-specific components if you wanted the code to work on the web because they're not written on top of ReactXP's cross-platform abstraction. My recommendation is to reach out to the folks at Expo and let them know that you're interested in having them support web as a platform, then see if they'd be interested in leveraging ReactXP to make that support available.

**Comment by vinils** [comment]
@erictraut I would kindly ask you to reconsider this.

**Reasons:**

- Less files, less bugs, support and maintenance
- As with react-native CLI (create-react-native-app), this can make it easier to people get involved and help/produce more
- Expo has many facilities, hot reload, publish and others

I´ve create a request https://github.com/Microsoft/reactxp/pull/236 with reactxp plus expo

**Comment by neelimabhukya** [comment]
how to make post method in reactxp

**Comment by dryganets** [comment]
If you are talking about HTTP POST - the XmlHttpClientRequest works the same way in react-native and web.
See https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest.

You also could use the following library:
https://github.com/Microsoft/SimpleRestClients/
