### ISSUE TITLE
How to use font awesome in reactxp 

### ISSUE THREAD

**Issue by adnan1naeem** [Microsoft/reactxp#218]
I am using  following code but can't  use fonts in it

var React = require('react');
var FontAwesome = require('react-fontawesome');
 
var MyComponent = React.createClass({
  render: function () {
    return (
      <FontAwesome
        className='super-crazy-colors'
        name='rocket'
        size='2x'
        spin
        style={{ textShadow: '0 1px 0 rgba(0, 0, 0, 0.1)' }}
      />
    );
  }
})

not working?

**Comment by ms-deregtd** [comment]
It looks like you'll need to wrap the two packages react-fontawesome and react-native-fontawesome into a reactxp extension, so it does the right thing depending on platform.  If you look in the extensions folder of reactxp you'll see some examples of platform-specific logic for the extensions.

**Comment by kmalakoff** [comment]
@ms-deregtd I followed the link here from https://github.com/Microsoft/reactxp/issues/217 assuming there would be an example based on your comment. 

Also, I see the concept of extensions mentioned here:  https://microsoft.github.io/reactxp/docs/extensions.html, but the information is incomplete or maybe a bit cryptic since after reading, it is not clear what to do.

Finally, I can't find good examples of reactxp extensions on npm leading me to wonder if others have been able to figure this out.

Maybe someone on the reactxp team could post a complete example here or a link to a sample github repo of how one might write an extension to reactxp for fontawesome since the question has been asked multiple times.

**Comment by erictraut** [comment]
There are four ReactXP extensions in the reacxp repo (in the extensions directory). You can use those as examples.

Let us know what information is misleading or missing in the documentation, and I’ll try to make it better.

**Comment by kmalakoff** [comment]
Thank you for explaining @erictraut. Let me know if I have been able to understand correctly...

Looking at the [extensions in reactxp](https://github.com/Microsoft/reactxp/tree/master/extensions)...in order to implement a cross-platform component, you would typically implement a default implementation at index.js for your module and then override the implementation using other index files in the form `index.[platform].js files`, where platform can be one of `ios`, `android`, `macos`, or `windows`.

This means that for font-awesome, you would expose the web one at `index.js` and override with the react native on `ios`, `android`.

Recommendations and feedback
-------------------

In the [documentation](https://microsoft.github.io/reactxp/docs/extensions.html):

1. add a link to the example extensions 

2. make it explicit and enumerate the platforms with explanations of what they are for. I'm not sure what `macos` and `windows` are for. Are they for electron apps running on those platforms? Add expected responses for questions like "Do you support linux or plan on it" + "why or why not"?

3. add an example of writing an extension on the documentation page since the only current example is how to use one, but most people would assume your just import and render them so it could be argued that the documentation is missing the use case that people may be looking for.

Thank you!

**Comment by erictraut** [comment]
Thanks for the feedback. Those are all good suggestions. I've updated the [Extensions documentation](https://microsoft.github.io/reactxp/docs/extensions.html) to include the requested information.

**Comment by kmalakoff** [comment]
Looks great. Thank you!

**Comment by omatrot** [comment]
@kmalakoff did you wrap a react-native and react-js module in an extension ? I'd like to do the same for https://github.com/oblador/react-native-vector-icons and https://github.com/sturmenta/react-js-vector-icons.
Thanks in advance.

**Comment by kmalakoff** [comment]
@omatrot I dropped using react-xp due to this odd level of workarounds. I just used react native and rect native web with webpack swapping in the implementation. Sorry!
