### ISSUE TITLE
Absolute Positioning an Animated.View

### ISSUE THREAD

**Issue by pixare40** [Microsoft/reactxp#222]
Is there a way to absolute position and animated view?

**Comment by pixare40** [comment]
Figured it out. By using the addCssProperty to the animated value

**Comment by erictraut** [comment]
I'm not sure what you mean by "addCssProperty method". This shouldn't be necessary. You can position an animated view absolutely just by using "position: 'absolute'" in its style definition. I recommend against animating the left/top/right/bottom position because this forces the React Native (or browser) layout engine to be invoked on every frame of the animation. It's far better to animate a translation transform to animate the position of an item.
