### ISSUE TITLE
Simple Tabs in reactxp 

### ISSUE THREAD

**Issue by adnan1naeem** [Microsoft/reactxp#238]
I wan to make simple tabs for navigation in reactxp. How can i implement them?

**Comment by dryganets** [comment]
If I started from scratch, I would try react-navigation.
It promises to have web support, and it has controls for tabs.

We have an internal SwipableTabView control which we have no plans to release publically yet.

You could try to make an extension for react-xp using this component for native:
https://github.com/react-native-community/react-native-tab-view
and this one for web:
https://github.com/StevenIseki/react-tab-view

You could use any extension we have as a template.

**Comment by erictraut** [comment]
@adnan1naeem, when you say "simple tabs", do you want to support gesture support (swiping between tabs)? That adds significant complexity. It can be done, but it requires significant amounts of code. As @dryganets mentioned, we developed such a component for the Skype app, but we don't have plans to release it publicly at this time because it would need to be made more generic. 

If you simply want to support tapping between tabs to switch the view, that's simple to do in ReactXP.
