### ISSUE TITLE
Question: .NET Integration?

### ISSUE THREAD

**Issue by Mike-EEE** [Microsoft/reactxp#28]
I am curious on how this integrates with .NET.  Is it (or will it be) possible to use .NET to build ReactXP applications?

**Comment by erictraut** [comment]
No, this solution is not at all related to .NET. ReactXP allows you to write apps that span web and native. Since web browsers don't support .NET code, that technology wouldn't be a good match. If you are a .NET developer and don't have a need for your app to run in a browser, I encourage you to consider Xamarin, which is a great cross-platform solution that builds on .NET and XAML.

**Comment by Mike-EEE** [comment]
Thank you for your reply, @erictraut.  Unfortunately, I am a .NET developer and I do want to run my application in the browser.  [And I am not the only one.](https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/10027638-create-a-ubiquitous-net-client-application-develo) ;)

It is pretty remarkable that MSFT continues to invest in technologies that perpetuate the developer divide in .NET and "web", when as you just pointed out in #21 the web is simply a platform (and the largest by far).  

As it is the largest platform at ~3.5 billion devices (and counting), it would seem that MSFT would invest into innovative technologies that would enable .NET in the browser process, rather than continuing to produce expensive, competing, and confusing offerings that only promote developer confusion (and cost for the organizations that employ them).

Anyways, rantoff. I appreciate your time and the reply.
