### ISSUE TITLE
RX.Accessibility.announceForAccessibility() leaves behind an hidden object which is reachable at least on MacOSX voice over

### ISSUE THREAD

**Issue by marco-ms** [Microsoft/reactxp#300]
Steps to reproduce the issue:
- On MacOSX have voice over enabled
- Have some code that calls RX.Accessibility.announceForAccessibility('some string here') only once
- Use Voice Over commands like Control+Option+[Left|Right] to navigate
- There is an hidden object that is left behind that still has the same text 'some string here' announced before (see screenshot)

A workaround to remove that hidden object is to call RX.Accessibility.announceForAccessibility('') with an empty string.

<img width="498" alt="screen shot 2017-10-05 at 11 18 38 am" src="https://user-images.githubusercontent.com/29441719/31292786-93f31d7a-aa89-11e7-8e8a-358dd88c3b62.png">

**Comment by erictraut** [comment]
@marco-ms, do you know if this is still an issue?

**Comment by marco-ms** [comment]
@erictraut yes it is in the 0.51 branch as well.
The problem is due to the hidden div created for announceForAccessibility

https://github.com/Microsoft/reactxp/blob/0.51.x/src/web/RootView.tsx line 334
Looking at this link[1] it seems possible that the role='text' is making it focusable, so I tried locally an example and using tabindex='-1' but it didn't fix the issue, the div is still focusable.

[1] http://accessibleculture.org/articles/2010/05/tabindex/

**Comment by roger4ever** [comment]
The problem still exists, it's caused by the hidden div created for announceForAccessibility. In addition, since the div has a default aria-role of group, the announced string will become "Group, ${announcement}"

The fix should be pretty simple, all you need is to add a few attributes to the hidden div:
aria-hidden="true" tabindex="-1" aria-label="" role="presentation" aria-live="assertive"

I believe the above attributes will hide the div from the screen reader object tree, and prevent the "group" being announced
