### ISSUE TITLE
Why does Popup.show() return false for invalid args, rather than throw an Error?

### ISSUE THREAD

**Issue by Fitzpasd** [Microsoft/reactxp#301]
When invoking `Popup.show()`, the logic returns a `false` if the input args are incorrect.  

```
// FrontLayerViewManager.tsx

if (!popupId || popupId === '') {
  console.error('FrontLayerViewManager: popupId must be valid!');
  return false;
}

if (!popupOptions.getAnchor()) {
  console.error('FrontLayerViewManager: getAnchor() must be valid!');
  return false;
}
```

Why is this preferred rather than throwing an `Error`?  I personally prefer the 'fail-fast' approach for libraries like this, both as an author and a consumer, so would like to understand why this approach is used instead.

**Comment by erictraut** [comment]
Yeah, I agree with you. A throw in this case would be preferable given that these conditions are never valid and are easily verified through simple testing. For more subtle or dynamic conditions, we try to avoid throwing exceptions because it forces callers to always include try/catch statements to protect against app crashes.

**Comment by Fitzpasd** [comment]
Thanks for the clarification.  Didn't want to create a PR without knowing whether or not this is a conscious design decision cross project.  

I'll create one tomorrow.
