### ISSUE TITLE
reactxp should migrate from legacy string refs api

### ISSUE THREAD

**Issue by asdanilenk** [Microsoft/reactxp#309]
String refs _are likely to be removed in one of the future releases_
https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs

**Comment by btraut** [comment]
Furthermore, string refs are a great way to break type safety.

Just a caution: It can be dangerous to use anon functions for setting refs. Because the anon method is different on each re-render, it'll call the previous anon ref method back with element=null, then call the new anon method with the new val. Using concrete methods prevents this first call.

**Comment by a-tarasyuk** [comment]
+1

**Comment by erictraut** [comment]
@asdanilenk, ReactXP currently supports both string refs and callback-based refs. This reflects the current React and ReactNative interface. We can and will remove support for string refs at the time that React and React Native do. Until then, I think we should keep them to avoid unnecessary breaks in existing code.

**Comment by asdanilenk** [comment]
@erictraut this isnt about supporting string refs, this is about the fact that reactxp uses string refs in  its own source, which is deprecated. It's fine if you want to keep it as is, just want to make sure my concern.

**Comment by erictraut** [comment]
Ah, I misunderstood. Yes, that's a good point. I'll keep it open as a work item.

**Comment by reseul** [comment]
@erictraut There seems to be no string ref left in ReactXP if I do the grep right.

**Comment by erictraut** [comment]
Yes, I removed all of these from the ReactXP core over the weekend. Forgot to close the issue.
