### ISSUE TITLE
UWP Connected Animations and RX.Animated

### ISSUE THREAD

**Issue by antonkh** [Microsoft/reactxp#349]
In the UWP "Fluent Design System" there is a feature called [connected animations](https://docs.microsoft.com/en-us/windows/uwp/design/motion/connected-animation). It basically allows to do the following:

1. Select the source UI element. Once selected, the element can be deleted. It's not necessary to delete it.
2. Select the target UI element. The element must be in the visual tree.
3. Start animation.

Animation doesn't affect UI elements: their properties remain the same. Instead it creates a picture that moves and transforms from one element to the other. This creates an illusion that the source element is transforming into the target element. `RX.Animated` is different: it changes properties and styles of the UI elements, but if we decide to introduce new API, `RX.Animated` seems to be the right place for it.

There are at least two approaches to expose this API:

1. In an imperative fashion, by replicating the UWP interface: there will be a `RX.AnimationService` with methods like `selectSource`, `selectTarget` and `startAnimation`. This would involve quite a bit of changes in RNW and RXP.
2. In a declarative fashion, by introducing new properties in `RX.View`, e.g. `animationSourceFor=123` to select the source element for animation with id `123`, then `animationTargetFor=123` and something like `animateWhen=rendered` to tell when to start the animation.

The second approach is easier to implement, but I'm afraid that the set of new properties won't be enough to describe all useful animation scenarios that could be otherwise described with the imperative approach. On the other hand the declarative approach could describe the most common scenarios and the imperative API could appear later if we decide we need it.

Any thoughts? @erictraut @rozele @rigdern

**Comment by erictraut** [comment]
I don't think this functionality belongs in ReactXP. It's very specific to UWP and has no analog on iOS/Android/web. 

Since it is platform-specific, I don't think it will be used much in RX-based apps. If/where it is absolutely required, app developers can write their own platform-specific code to access it.

It still may make sense to expose those via RN-UWP (as opposed to leaving it up to developers to write their own RN-UWP native module), although I would think that it's a low priority compared to the other missing functionality in RN-UWP. If it is built into RN-UWP, it should probably expose the imperative interface.

**Comment by antonkh** [comment]
Makes sense. Let's go with the native module approach then.
