### ISSUE TITLE
touchmove not being used for web

### ISSUE THREAD

**Issue by Iamsamwhoami** [Microsoft/reactxp#356]
Is there a reason for why touchmove isn't used as an input in `GestureView`?

**Comment by erictraut** [comment]
Can you provide more context? I guessing that you're asking about the implementation of GestureView on a particular platform?

**Comment by Iamsamwhoami** [comment]
Yeah, of course.

[GestureView](https://github.com/Microsoft/reactxp/blob/master/src/web/GestureView.tsx) seem's to use a custom PanResponder implementation called [MouseResponder](https://github.com/Microsoft/reactxp/blob/master/src/web/utils/MouseResponder.ts), looking at the code for MouseResponder it doesn't seem that it uses `touchmove` as an input (makes sense due to the name) though this makes the `GestureView` practically useless on any touch device when running the app in a browser.

Is this expected behaviour, a miss in the implementation, or a bug?

**Comment by erictraut** [comment]
Ah, you're talking about the web implementation. We (the Skype team) had no need for GestureView to provide touch support in the browser. The touch-centric platforms (Android and iOS) have their own native implementations. That's why my current implementation focuses entirely on mouse, track pad, and scroll wheel.

I personally don't have much experience with touch support on the web, and I haven't researched whether it's been standardized across all major browsers. It's still not a priority for the Skype team, but if it's something you need, I think it would be a fine addition to the web implementation of RX.GestureView.

**Comment by Iamsamwhoami** [comment]
Ah, okay!

Most mobile browsers have a very capable touch support actually: https://caniuse.com/#search=touchmove

I might put some work on it and submit a PR if I find the time.

Thanks!

**Comment by derolf** [comment]
I am hitting the same issue. Any workarounds?
