### ISSUE TITLE
Button ignores the cursor style

### ISSUE THREAD

**Issue by pronebird** [Microsoft/reactxp#402]
Hi,

I am unable to remove the cursor from a `<Button>` component.

```
const styles = Styles.createViewStyle({ cursor: 'default' });
return (
  <Button style={ styles } onPress={ this.props.onClose }></Button>
);
```

Problematic LOC: https://github.com/Microsoft/reactxp/blob/master/src/web/Button.tsx#L170

Workaround is to add `cursor='default'` to the attributes. 

This seems like a legacy of Windows dominated web platform. If you look at modern macOS UIs for example you will only find the hand cursor when hovering over links which very rare apps place somewhere in about boxes or exercise in few other use cases when user needs to be taken to the web browser.

**Comment by erictraut** [comment]
Good find. I didn't realize that "cursor" was exposed as both a prop and a style attribute for RX.Button. It was meant to be exposed only as a style attribute, as it is with RX.View. 

I've modified the code to override the style with 'pointer' if it is not otherwise specified. I understand your point about "legacy of Windows dominated web platform", but it is pretty standard for web apps to use a pointer for buttons. See github, for example. :) If you want the Mac UI standard (with no pointer), you can always override with "default" in the style definition.

Here's the new code. Let me know if this addresses the issue to your satisfaction.

```
// Default to 'pointer' cursor for enabled buttons unless otherwise specified.
if (!combinedStyles['cursor']) {
    combinedStyles['cursor'] = this.props.disabled ? 'default' : 'pointer';
}
```

**Comment by pronebird** [comment]
@erictraut seems reasonable to me! Do you think you could release the patch anytime soon?

**Comment by erictraut** [comment]
It's already checked in, so you can rebuild the library if you want it immediately. 

The next version of ReactXP that I publish will be a pre-release version (0.51.x). I don't have an exact ETA for that yet. Could be a couple of weeks.

**Comment by pronebird** [comment]
This issue is back! 😭
