### ISSUE TITLE
Is navigator being dropped or not?

### ISSUE THREAD

**Issue by robeeeert** [Microsoft/reactxp#464]
Hi, I am a bit confused, because I read through the comments in issue #9 , where you eventually announce that the whole navigator extension will be dropped: https://github.com/Microsoft/reactxp/issues/9#issuecomment-312391920

Nonetheless there are still updates to that extension and it is mentioned nowhere else. Did you change plans? What is the current status of the navigation extension?

Greets, Rob

**Comment by erictraut** [comment]
After the discussion in issue #9, we decided to remove support for the RX.Navigator namespace from ReactXP core. We then brought it back a few months later as an extension, which we have been maintaining since then. It is [fully documented](https://microsoft.github.io/reactxp/docs/extensions/navigator.html).

**Comment by robeeeert** [comment]
Thank your for the clarification!
