### ISSUE TITLE
Color transition animation not interpolated

### ISSUE THREAD

**Issue by zarubond** [Microsoft/reactxp#490]
The toggle switch in hello-world sample https://github.com/Microsoft/reactxp/blob/master/samples/hello-world/src/ToggleSwitch.tsx has an animation bug. When you click on the toggle, its background color should be gradually changed from '#66f'  to '#ddd'. But currently the color is only switched at once without any transition.

**Comment by erictraut** [comment]
Good find. This was a bug in ReactXP's web animation code. It affects only those attributes that are made up of multiple words (like "backgroundColor"). The code was specifying the transition attribute using camel case (e.g. "backgroundColor") rather than CSS-style (e.g. "background-color"). 

The fix will be included in the next published release of reactxp.

**Comment by erictraut** [comment]
We've decided to back-port this fix to the stable branch (0.51.x). It will be included in 0.51.7 the next time we publish.
