### ISSUE TITLE
ReactXP.App.getActivationState() can return undefined

### ISSUE THREAD

**Issue by berickson1** [Microsoft/reactxp#532]
On iOS it's possible for ReactNative.AppState.currentState to be 'unknown' (when iOS app state is 'inactive' on start), which isn't in the _rnStateToRxState array. This results in the getActivationState() call returning undefined.  I'm not sure if we should add a new state for Unknown or treat it as an existing state.

I'm going to try to address in react-native as well and contribute back to them, but we should still handle in reactxp for back-compat reasons

**Comment by berickson1** [comment]
I'm happy to create a PR, but want to figure out expected behaviour beforehand :)

**Comment by erictraut** [comment]
We should use one of the existing states rather than create a new "unknown" state.

**Comment by berickson1** [comment]
I agree, but should it be active, inactive or background. Active is likely the most forgiving, but could result in poor background if we rely on the status.

In all the cases I've seen so far, 'unknown' was reported when we should actually be in an active state, but that's anecdotal evidence at best

**Comment by erictraut** [comment]
@berickson1, any update on this issue?

**Comment by berickson1** [comment]
Im still unsure what state we should use when unknown... probably active.
Thoughts?

**Comment by erictraut** [comment]
Yeah, I agree it should be active on launch.

This change may be more complex than I initially thought. Because our internal notion of the app's activation state won't always match the value in RN.AppState.currentState, we'll need to allocate our own variable to track our current notion of the state. Then we'll need to make sure the event triggering mechanism calls "fire" only if our notion of the value changes. Otherwise callers will see the event triggered even when the state apparently didn't change.

**Comment by berickson1** [comment]
The current mechanism already has the issue of over-eventing. I've got a PR up to at least mitigate bad behaviour. It's easy to store last state although that would introduce a behavioural change from what we currently have :)
