### ISSUE TITLE
Percentage values

### ISSUE THREAD

**Issue by stijnvanderlaan** [Microsoft/reactxp#545]
FlexboxParentStyle requires a number for width/height etc. but should also accept strings for percentages.

**Comment by erictraut** [comment]
We've made a conscious decision not to support percentage-based parameters. RN didn't support them until recently. They are almost always unnecessary (i.e. there are other ways to get the same behavior), and they slow down attribute parsing and layout.

**Comment by stijnvanderlaan** [comment]
Can you explain this to me, what other ways?

**Comment by erictraut** [comment]
It depends on what you're trying to do. Can you explain more about what you're trying to achieve. Often, you can use flex:grow and flex:shrink values that are in proportion to the desired percentages.

**Comment by kg-currenxie** [comment]
Re-opening this one. 
You should strongly re-consider, since it's officially supported now: https://facebook.github.io/react-native/docs/flexbox#width-and-height

### Both width and height can take following values:
- **auto** Is the default Value, React Native calculates the width/height for the element based on its content, whether that is other children, text, or an image.
- **pixels** Defines the width/height in absolute pixels. Depending on other styles set on the component, this may or may not be the final dimension of the node.
- **percentage** Defines the width or height in percentage of its parent's width or height respectively.
