### ISSUE TITLE
how to deploy my reactxp app for web?

### ISSUE THREAD

**Issue by TheLoopCompany** [Microsoft/reactxp#556]
Hello! im  trying to deploy my aplication with zeit now, but i dont know how .. any reference? or another way to deploy my aplication will be great.

**Comment by erictraut** [comment]
A reactxp web app is like any other web app when it comes to deployment. The details will depend on which web server and hosting/cloud service you choose.

**Comment by TheLoopCompany** [comment]
I need t

**Comment by TheLoopCompany** [comment]
In web for deployment i run npm run build.. But un reactxp doest not work. How i do it?

**Comment by erictraut** [comment]
Are you attempting to build the reactxp library? Or build your app, which uses the reactxp library? You shouldn't need to build the reactxp library because it's published through npm in a form that can be consumed directly by your app. I recommend looking at one or more of the reactxp sample apps like [this one](https://github.com/Microsoft/reactxp/tree/master/samples/hello-world).
