### ISSUE TITLE
Typecheck error of RX components like View

### ISSUE THREAD

**Issue by devin6391** [Microsoft/reactxp#560]
Hi I am getting typecheck error from typescript if I import RX components like this:
```
import {
    Component,
    View,
    TextInput,
    Button,
    Text
} from 'reactxp';
```

The error is:
```
[ts] Cannot find name 'RX'.
(alias) type View = RXInterfaces.View
(alias) var View: typeof RXInterfaces.View
import View
```

I am getting error on each line where I use these components. I am using them like this:
 ```
             <View>
                <TextInput placeholder="Enter your Name" value={name} onChangeText={this.handleNameChange} />
                <TextInput placeholder="Enter a name for the session" value={sessionName} onChangeText={this.handleSessionNameChange} />
                <Button title="Create" onPress={this.handleCreate}>Create</Button>
                {hasError && <Text>Please enter the name</Text>}
            </View>
```

**Comment by erictraut** [comment]
When the TypeScript compiler encounters JSX blocks, it converts them into calls to XXX.createElement. By default, "XXX" is "React". When you're using ReactXP, however, the tsconfig file is changed to use "RX" instead. Because of this, you need an import statement like this:

import RX = require('reactxp');

You can then use RX.View, RX.TextInput, RX.Button, etc. within your code.

**Comment by erictraut** [comment]
If you don't like "RX" for some reason, you can use a different import name of your choosing. Just make sure to use the same name in the import statement and in the "reactNamespace" value in your tsconfig.json file.
