### ISSUE TITLE
Public API to access Animated.Value._getValue()

### ISSUE THREAD

**Issue by pronebird** [Microsoft/reactxp#578]
Hi,

I realize that `Animated.Value._getValue()` is not public for a reason. I am interested in inspecting this value after the animation is stopped to be able to calculate the proper duration when reversing animation such as if 1s animation is being stopped and reversed half way through I'd like the reverse animation to run for 0.5s only. `onLayout` seems to be less reliable in that sense on the web but `Animated.Value` extracts the precise value from DOM.

Any plans to make that part of API public?

Cheers,
Andrej

**Comment by erictraut** [comment]
No, the value of an animated value can't be accessed for good reason. On RN, the animation occurs on the other side of the RN bridge, so there's no way to synchronously query the value of a value. Even on the web, the CSS engine operates asynchronously from the JS thread, so any attempt to query the value will necessarily return inaccurate information.

onLayout is reliable in the sense that it will eventually be called, but for performance reasons, we defer and batch onLayout calls. There's no guarantee on either the web or RN that onLayout will be called immediately when a layout change occurs. It's all asynchronous.

I think the best solution to your problem is to use time (rather than the animated height) to compute the height delta. In other words, record the time when you call start(), then compute the delta when you call stop(). Divide by the total animation time to get the approximate percentage of the height change that has occurred before the animation was stopped. This won't be exact because you're applying an easing curve, but I think it will still have the effect you're looking for.

**Comment by pronebird** [comment]
I implemented the solution that you proposed and it performed very well but it is certainly more complex since it adds a lot of state and maintenance. 

I swapped it with `UserInterface.measureLayoutRelativeToWindow` which works fine and I don't mind it to be asynchronous as long as it doesn't take a significant amount of time which I hope it shouldn't. 

Thanks for brainstorming with me! 👍
