### ISSUE TITLE
No screenshots

### ISSUE THREAD

**Issue by paulcbetts** [Microsoft/reactxp#6]
There are pages and pages of documentation and a landing site, yet not a _single_ screenshot in sight. What does this actually look like?

**Comment by brunolemos** [comment]
I thought the same. Also, react-native has a live simulator in their docs, doesn't Microsoft have anything similar? If not, the ios/android simulator would help already.

**Comment by erictraut** [comment]
We're still working on the documentation and site. Feel free to contribute PRs if you'd like to add to it.

We didn't include screenshots because ReactXP is built on top of React Native, so apps written to ReactXP look just like a React Native app. If you want to see a full app built with ReactXP, you can download the "Skype Preview" Android client in the Google Play Store. We haven't yet released the iOS or other versions except as closed (by-invitation) betas, but those will be available at some point in the future.

Also, keep in mind that the components in ReactXP are intentionally basic so they can be used as building blocks for more complex components. As such, they're not very interesting from a visual perspective. A screen shot of a View, ScrollView or Text component would be pretty uninteresting, after all.

Over time, we'll publish more samples that show how more complex components can be built from these primitives.

**Comment by paulcbetts** [comment]
> We didn't include screenshots because ReactXP is built on top of React Native, so apps written to ReactXP look just like a React Native app.

Sure, but you have to remember, people who find the project don't know that. The screenshot conveys that super quickly

**Comment by brunolemos** [comment]
Correct
