### ISSUE TITLE
Support for zIndex

### ISSUE THREAD

**Issue by junseld** [Microsoft/reactxp#600]
Is it possible to add support for `zIndex`? 
or what are the drawbacks/problems to do so?

related issue (react-native supports zIndex.): https://github.com/Microsoft/reactxp/issues/452

I'm not sure if you just are ok with the workarounds and didn't have the time to add it or if there is another problem I missed.

**Comment by junseld** [comment]
btw I currently just use a workaround:
```
const style = RX.Styles.createViewStyle({ 
    ['zIndex' as any]: 1 
}
```

**Comment by erictraut** [comment]
I'd prefer not to add zindex. In my experience, there's always a cleaner way to implement something without using zindex. I'd be more inclined to add it if zIndex were implemented in a consistent fashion across all supported implementations of RN, but that's not currently the case. It has been added to iOS and Android, but they have different behaviors and limitations.

If you have a specific use case in mind for zindex, let's discuss and see if I can convince you that there's a cleaner way to accomplish your objective.

**Comment by junseld** [comment]
ah ok didn't know they had different behaviors.
I just wanted my titlebar to show its shadow (without column-reversing their render order)
after some try&error it worked with that workaround I postet (but didn't test it for iOS yet).

currently I mainly need it for that.

**Comment by erictraut** [comment]
Yeah, column reversing is an easy workaround in your case.

Or if your titlebar is a static height, you can render in normal-column order but leave space at the top. Then include your actual title bar at the end of the item list and use "position: absolute" so it is positioned where you want it.

**Comment by junseld** [comment]
ok thanks. yeah for now setting the zIndex here works pretty good.
But I will keep it in mind for similar cases in the future, thanks.

should I close this issue? I know know why you didn't add zIndex and can understand it (even if I would still like to have it :P)

**Comment by shameister** [comment]
Hey Eric,

 we ran into a similar issue. We are creating a custom component, which shows an input field and auto-suggestions, when typing. We like to reuse our component in several parts of our code, by just using `<TextInputFilterable>`.

![bildschirmfoto 2018-06-11 um 18 13 29](https://user-images.githubusercontent.com/98413/41243730-31d20efc-6da3-11e8-8b5b-58d72ee7cd04.png)
![bildschirmfoto 2018-06-11 um 18 13 31](https://user-images.githubusercontent.com/98413/41243729-31a1d7aa-6da3-11e8-90ba-4e13f4dff1ab.png)


Later on, we like to provide this component as an open source extension for ReactXP. In my opinion it would be counter-intuitive to explain everyone, you have to reverse the order to use it. We like to use it as a drop-in replacement for TextInput.

I'm looking forward to your suggestions and find out, what would be the best way to make our component as easy to use as TextInput for everyone.

Regards,
Sascha

**Comment by erictraut** [comment]
That's a good example of something that's difficult to do without zIndex support. I implemented a similar functionality in the Skype client, but with my approach, it wouldn't be possible to package it as a custom control that can be dropped in anywhere. It required coordination from a view higher in the view hierarchy — one that could render the popup menu above the other contents.

Let me discuss with the owners of the various RN implementations to see if they have any concerns with supporting zIndex in a consistent manner.

**Comment by erictraut** [comment]
I had a quick discussion with a few other members of the community. Here's the problem with zIndex. It is implemented inconsistently across platforms. On the web and on Windows UWP, it applies globally. On iOS and MacOS, it applies only to sibling views at the same level of the view hierarchy. It's not clear from the documentation which approach Android uses, but I suspect it's global.

Those are significant differences in behavior, and I don't see any way that we could expose the style attribute in ReactXP in such a way that it would be generally useful for cross-platform apps. 

I think our options are:
1. Stick with current limitations, which would mean that you'd need to use render ordering to enforce z ordering. This wouldn't allow you to write a TextInputFilterable control that has an ideal, clean interface.
2. Expose zIndex and document it as having inconsistent behavior. I think this would allow you to implement your control but will also result in confusion and a stream of support issues because of the inconsistency.
3. We could look at adding support in RX.Popup for non-modal popups. This issue came up in a [PR that was recently submitted](https://github.com/Microsoft/reactxp/pull/669). and I've been thinking about how to address it. We might be able to address both issues with one solution.

**Comment by pronebird** [comment]
ps: IIRC `z-index` on the web platform applies to sibling elements within the `position: relative` container – not globally.

**Comment by Bonobomagno** [comment]
An other limitation is when you use zIndex on Android: never works as espected. You can use elevation(on android), but elevation bring also a boxshadow.
I think that the best solution is to use a custom one propriety (heightXP in this case? idk ) with 3-4 different platform specific implementation of this.

**Comment by erictraut** [comment]
I don't see a way to implement zIndex in a cross-platform manner with consistent behavior, so closing this.
