### ISSUE TITLE
Platform specific functionality is loading on all platforms while it is not supposed to

### ISSUE THREAD

**Issue by Roye7777777** [Microsoft/reactxp#626]
Hi all,

I am experimenting with ReactXP and at the same time getting to know React. As one thing I try I use the ImageCropPicker library to let Android and iOS use the camera. Implemented, I use a component which I named NativeUploader with this in it:

```
// ... imports, styles etc.

class NativeUploader extends RX.Component {

    constructor(props: any) {
        super(props)
    }

    render() {
        return (
            <RX.Button style={ styles.roundButton } onPress={ this._pickAnImageNative }>
                <RX.Text style={ [styles.titleText] }>
                    Pick an image
                </RX.Text>
            </RX.Button>
        )
    }

    private _pickAnImageNative = () => {
        ImagePicker.openCamera({
            width: 300,
            height: 400,
            cropping: true
        }).then(image => {
            // do something with the image
        });
    }
}

export default NativeUploader;
```

But, as web does not support these kinds of native functionalities, my `npm run web-watch` is going wild in echoing tens of errors in not being able to resolve modules like this:

```
ERROR in ./node_modules/react-native/Libraries/react-native/react-native-implementation.js
Module not found: Error: Can't resolve '[...]' in '/Users/[...]/Projects/[...]/samples/hello-world/node_modules/react-native/Libraries/react-native'
```

This is logical, because, as said, functionalities like 'takeSnapshot' are nonexistent on the web. My web simulator is not displaying anything, while the native simulators actually do. For the web I then want to use:

`<input type="file" onClick={ this._pickAnImageWeb } />`

which also appears to work in RXP. I am aware there are functions to check for platform, like RX.Platform.getType() or even RX.Platform.select(), like this

```
if (RX.Platform.getType() == 'web') {
    return (
        <WebUploader/>
    );
} else {
    return (
        <NativeUploader/>
    )
}
```

But, when I implement this, it loads everything, causing the web app to crash instantly despite checking for the platform. Perhaps I am forgetting something important here, but still, my question: is this kind of platform specific library functionality filtering like this possible in a way, where the native functionality is not being used in web, and web functionality is not being used in native? Qua rendering everything is going fine after all: in web the HTML-button is showing and in native the appropriate `<RX.Button>` is appearing. It's just the `ImagePicker.openCamera()` that's causing the issue.

For what it's worth: I am working this out in the hello-world sample. And yes, I'm aware, a [comparable issue exists already](https://github.com/Microsoft/reactxp/issues/390) except in my case my intention actually is developing for native _and_ web. 

Thanks!

**Comment by erictraut** [comment]
This is a great example of where it makes sense to implement a [ReactXP extension](https://microsoft.github.io/reactxp/docs/extensions.html). With this approach, you can implement the functionality for different platforms (e.g. native vs web) and "link" the appropriate implementation at build time. The existing build tools (webpack, RN loader, etc.) automatically bind the correct version based on the file suffix (index.js, index.ios.js, index.android.js, etc.). For an example of how to write a ReactXP extension, see the [reactxp-video code](https://github.com/Microsoft/reactxp/tree/master/extensions/video). 

Another approach (a little less elegant) is to use a build-time aliasing mechanism like the one I describe in [this blog](https://microsoft.github.io/reactxp/blog/2017/06/29/asset-loading.html).

Yet another approach (which is even less elegant, but easier to implement) is to move the imports into your conditional runtime logic. We used to use this approach, but we moved away from it because it eliminates type safety provided by TypeScript, and it makes the code more difficult to maintain.

```
if (RX.Platform.getType() == 'web') {
    let WebUploader = require('./uploader/web-uploader');
    return (
        <WebUploader/>
    );
} else {
    let NativeUploader = require('react-uploader');
    return (
        <NativeUploader/>
    )
}
```
