### ISSUE TITLE
Correct way to do a cross-platform network request in ReactXP / API fetch

### ISSUE THREAD

**Issue by kokizzu** [Microsoft/reactxp#65]
I tried to use `fetch` but it seems not available in ReactXP?

```
  fetch(Res.Endpoint.Login) // ...
```

it shows:

```
ERROR in [at-loader] ./src/LoginPage.tsx:103:4 
    TS2304: Cannot find name 'fetch'.
```

**Comment by berickson1** [comment]
@kokizzu, if you're confident that the browser you're using will have fetch support, you can use the typings from @types/whatwg-fetch and you should be able to start using it.  If you're not confident in this, you'd have to include some sort of a polyfill (like whatwg-fetch).  We didn't want to make the assumption that all browsers will support fetch, since there are so many browser combinations on the market.

**Comment by erictraut** [comment]
I added documentation for an extension that provides a helpful wrapper around any REST API. This isn't technically a ReactXP extension - it can be used independently of ReactXP, but they work well together.

https://microsoft.github.io/reactxp/docs/extensions/restclient.html
