### ISSUE TITLE
Activation state change event is not fired when running in Electron environment

### ISSUE THREAD

**Issue by pronebird** [Microsoft/reactxp#661]
I observe that `activationStateChangedEvent` is never triggered when running on Electron (web).

```
App.activationStateChangedEvent
        .subscribe((activationState) => {
          console.warn('activationState = ' + activationState);
          // Never happens
        });
```

Standard window `blur` and `focus` events fire properly when I hide/show the browser window.

Probably related to the use of `ifvisible` library. Tested with RX 1.1.0

**Comment by erictraut** [comment]
Could you test with the latest build of RX (1.3.0-rc.6 or newer)? We've eliminated the dependency on ifvisible, but I suspect the same problem may still occur. It depends on whether Electron passes through the window-level focus/blur events to the hosted javascript.

**Comment by pronebird** [comment]
@erictraut I'll test it tomorrow 👍

**Comment by pronebird** [comment]
@erictraut it works for me on Electron 2.0, but I remember that `window.blur` and `window.focus` worked on Electron 1.8 too. Good work! 👍

**Comment by pronebird** [comment]
@erictraut  Was there any regression since 1.3.0 stable?

I am facing the same issue now, basically that's the code in my component:

```
    window.addEventListener('focus', () => {
      console.log('window.focus');
    });
    window.addEventListener('blur', () => {
      console.log('window.blur');
    });

    this._activationStateToken = App.activationStateChangedEvent.subscribe((activationState) => {
      console.log('activationStateChangedEvent: ', activationState);
      if (activationState === Types.AppActivationState.Active) {
        this._refreshAccountExpiry();
      }
    });
```

`activationStateChangedEvent` is never printed, but focus/blur events on `window` work fine.

**Comment by erictraut** [comment]
Before publishing 1.30, we needed to remove the activation state change relating to window-level focus/blur on desktop platforms. It caused regressions in existing code. If you have a need for this functionality and want it to be part of the RX platform, we'll need to find a way to add it that doesn't break existing code. I think we can do this by introducing another state in the AppActivationState enumeration. The previous code tried to reuse the Inactive state, which was causing problems.

**Comment by pronebird** [comment]
@erictraut good point. I haven't looked at the code much, but it seems that there was a regression because reactxp does some heuristics before transitioning to the next state?

**Comment by erictraut** [comment]
The regression was due to assumptions that apps had made about the existing states — in particular, the Inactive state. @RamyaSenk implemented these changes and discovered the regression, so we should loop her in to the discussion. Ramya, any thoughts here?

**Comment by RamyaSenk** [comment]
Initially in ReactXP there were only two states in Web and Electron, 
1) Active - It is active when app is in foreground i.e. not minimized - whether focused or blurred it does not matter.
and 2) Background- It is background when app is minimized. 

I introduced a new state "Inactive" from 1.3.0-rc.4. when app is not minimized but blurred - to help apps distinguish when app is blurred but in the foreground.

But it caused regressions in apps using existing behaviour. For example they would rely on events being fired only when app is minimized or not minimized and have some app logic based on that like running background tasks and foreground tasks. But now with the "Inactive" state we would be breaking those assumptions and it was difficult to find a clean workaround with this new state. 

Hence i reverted this change and it went back to existing 2 states which fires when app is minimized and not minimized since 1.3.0.  

I dont think there is any difference in this particular behaviour between electron and web. I think the best way to provide this "Inactive" State is introducing a new enum like @erictraut said. Without causing confusion on the behaviour for other platforms. 

Maybe we could just have a foucs/blur state. 

1) Web/electron -> fires focus when window is focused, fires blurred when window is blurred. Assuming we always have one window in this case. 
2) On RN mobile -> Fires Focus when AppActive state is active. Fires blur when AppActive state changes to Inactive/Backgrounded from Active
3) On RN Windows -> Here we need the window id that the listener is tracking and fire focus/blur based on that maybe. This we need to investigate to figure out if this is possible. 

What do you think?
