### ISSUE TITLE
Tutorial on updating reactxp

### ISSUE THREAD

**Issue by kokizzu** [Microsoft/reactxp#70]
It would be great if the documentation added with tutorial for upgrading, for example when upgrading from `0.42.0_rc.1` to newer release later.

**Comment by erictraut** [comment]
Unless otherwise noted, upgrades should be as straightforward as just updating the version in your app's package.json file and rebuilding. We will try to avoid making breaking changes to the interface. Where these are required, we'll note them in the [Versions](https://microsoft.github.io/reactxp/versions/version_history.html) page in the documentation.
