### ISSUE TITLE
How to get "this" context from TextInput event

### ISSUE THREAD

**Issue by kokizzu** [Microsoft/reactxp#71]
I tried to set `state` from `TextInput`, but `this` refers to the object not the parent

```
class Foo extends RX.Component<void, AppState> {
	constructor() {
		super();
		this.state = {
			loginEmail: '',
		}
	}
	
	render() {
		return <RX.View style={ss.container}>
				<RX.Text style={ss.label}>via E-Mail or Mobile Phone</RX.Text>
				<RX.TextInput style={ss.input} value={this.state.loginEmail} onChangeText={this.onLoginEmail} />
			</RX.View>
		</RX.View>
	}
	
	onLoginEmail(val: string) {
                // this refers to TextInput, instead of Foo object
		this.state.loginEmail = val;
	}
	
}
```

How to get the this contect to refer to Foo object, so I can change the `state` value?

Should we pass `this` property as attribute one by one for each component? 

Or is there a better example similar to `Vue`/`Angular` two-way binding?

**Comment by popealex** [comment]
Can` onChangeText={this.onLoginEmail}` to `onChangeText={() => {this.onLoginEmail();}}`

**Comment by erictraut** [comment]
The approach suggested by popealex will work, but it will cause React to do extra unnecessary work because each time the render occurs, a new "bound" version of your callback will be constructed and passed to onChangeText. This will cause React's diffing engine to think that a prop has changed.

To avoid this, I recommend doing the following instead:
```
private _onLoginEmail = (val: string) => {
    this.setState({ loginEmail: val });
}
```
This creates a "pre-bound" variable that you can then pass safely as a prop.

Note that I've also specified that it's private and used the convention of an underscore to indicate that it's private. This isn't required, but it's considered a good practice.

And finally, note that it's important to call this.setState rather than modifying the state object directly. By calling setState, React will merge the specified partial state into the state object and call render() again.
