### ISSUE TITLE
[FeatureRequest] Add callback to VirtualListView for visible item changes

### ISSUE THREAD

**Issue by Fitzpasd** [Microsoft/reactxp#727]
It's very difficult for users of the VLV to know when their components are actually on screen since the virtualization is handled internally and the regular component lifecycle methods aren't invoked.

This feature request is to add a callback prop to VLV that gets invoked when the on-screen contents have changed.  A similar API exists on react-natives [VirtualListView](https://facebook.github.io/react-native/docs/virtualizedlist#onviewableitemschanged)

**Comment by erictraut** [comment]
@Fitzpasd, were you planning to submit a PR for this? Or did you find a workaround?

**Comment by Fitzpasd** [comment]
We ended up using RN's FlatList due to this and #728.  Both are issues I was hoping to investigate, but haven't had free time yet.

**Comment by nickfloop** [comment]
Would such a feature also make it possible for VirtualListView items to have onPress and similar event-based methods? Specifically, (this example is based on the example in the [ReactXP VirtualListView](https://microsoft.github.io/reactxp/docs/extensions/virtuallistview.html) docs) I am looking for a way to add onPress to items, such as:
```javascript
    private _onPressChild = (e: RX.Types.SyntheticEvent) => {
        e.stopPropagation();
        console.log('CHILD');
    }

    private _renderItem(item: FruitListItemInfo, hasFocus?: boolean) {
        const viewStyle = RX.Styles.createViewStyle({
            height: item.height,
            backgroundColor: item.template === _headerItemTemplate ?
                '#ddd' : '#fff',
            alignItems: 'center'
        }, false);

        return (
            <RX.View style={ viewStyle } onPress={this._onPressChild}>
                <RX.Text>
                    { item.text }
                </RX.Text>
            </RX.View>
        );
    }

```
This snippet does not actually work because clicking on a VirtualListView item does not log to the console.

I believe this is related to this feature request, but I may be mistaken.

As an aside, great work with ReactXP. It's been a joy to use so far.

**Comment by erictraut** [comment]
What you're trying to do should work fine. Virtual List Items can receive input events just like any other views. I recommend using an RX.Button to accept onPress because it will also provide the proper feedback on iOS and Android, and it will be treated as a button from an accessibility perspective. 

For an example of a Virtual List Item that uses an onPress handler, check out [this sample](https://github.com/Microsoft/reactxp/blob/master/samples/TodoList/src/ts/views/TodoListItem.tsx).

**Comment by settjesilixon** [comment]
I'm an idiot.

`private _renderItem(item: FruitListItemInfo, hasFocus?: boolean)` should be `private _renderItem = (item: FruitListItemInfo, hasFocus?: boolean) => `

**Comment by erictraut** [comment]
Yep, that would do it. :)

**Comment by erictraut** [comment]
No progress on this feature request for a long time, so closing.
