### ISSUE TITLE
Can I use third party components like recharts?

### ISSUE THREAD

**Issue by spoeck** [Microsoft/reactxp#76]
Of course [recharts ](https://github.com/recharts/recharts) wouldn't  work if I build it for React-Native, but I want to integrate it for the web.

Is it possible to use existing components from React or React-Native?

**Comment by erictraut** [comment]
Yes, you can use existing components for React and React Native, but the React components will obviously run only on web and the React Native will run only on iOS and/or Android. To develop a component that runs across all platforms, you'd need to create a common interface (same props and APIs) that wraps the React Native component and provides a similar implementation on the web (or vice versa).

For example, if you wanted to implement video playback, you could use a React Native component like [react-native-video](https://www.npmjs.com/package/react-native-video), which provides support for iOS and Android. You would then need to implement a web solution (probably based on HTML5 video tags) if you want the same component interface for the web. I use this example because it's how we've implemented our video playback component. We'll probably release this as a reactxp extension in the near future.

If you don't need the component to run on native (or conversely on web), then you can include it conditionally based on the platform target.

**Comment by spoeck** [comment]
Thanks for your fast reply.

I want to do this...

> If you don't need the component to run on native (or conversely on web), then you can include it conditionally based on the platform target.

...because I have a web-only project. The reason why I want to build components with reactXP is, that I can use some components for other mobile projects. It's not necessary that the whole project runs on all platforms, we just want to share components between projects.

I'm also new on TypeScript, but I like it. So if I want to import a normal 3 party component, how I can import it? Do I have to write a definition file? Or can I import it as usual e.g: 

`import {BarChart} from "recharts";`
which was installed with `npm i --save recharts`

**Comment by erictraut** [comment]
By default, TypeScript doesn't require type definitions. It will infer a type of "any" for methods that it doesn't know about. This allows you to compile any existing JavaScript as valid TypeScript. However, we recommend configuring TypeScript to require types for everything (i.e. it's an error to have an inferred "any" type). This allows you to take full advantage of type safety for detecting bugs and improving programming efficiency. Type definition files are available for most common libraries on [definitelytyped](http://definitelytyped.org/). If you can't find a type definition, it's easy to create one.

**Comment by spoeck** [comment]
Ok, thank you for your detailed answer. I will check this out!

**Comment by afilp** [comment]
@erictraut 
This is great!
I am interested for the video component, when are you planning to release it inherently?

**Comment by erictraut** [comment]
@afilp It's the next extension on my to-do list. I'll try to find time in the next week to complete the documentation, clean up the code, and publish it.

**Comment by erictraut** [comment]
@afilp I just published the reactxp-video extension. Here's the [documentation](https://microsoft.github.io/reactxp/docs/extensions/video.html). I also updated the hello-world sample to demonstrate how to use it.

**Comment by dedmakap** [comment]
@erictraut 
> If you don't need the component to run on native (or conversely on web), then you can include it conditionally based on the platform target.

I would greatly appreciate the hints about this part. I'm pretty new to react in general so it's a mystery to me. I'm just installing the packages via npm and including what I need where I need it. It would be very cool to see examples of such conditional including depending on platform or smth like that in demo samples.
