### ISSUE TITLE
Image Background

### ISSUE THREAD

**Issue by junseld** [Microsoft/reactxp#769]
Hey,
when do you plan to make a new release with the image background changes?
commit: https://github.com/Microsoft/reactxp/commit/36c9f172a3b99cbbf5173d4d437f85dee7dd304d

and what is the reason to not use `ImageBackground`?

Thanks

**Comment by erictraut** [comment]
This support is in 1.3.3, which I published a few days ago.

The internal implementation doesn't use RN.ImageBackground because this component was introduced in RN relatively recently, so if we take a dependency on it in RX, we'll break compatibility with earlier versions of RN. RN.ImageBackground is a simple wrapper that effectively does the same thing that our internal RX.Image component now does, so there's no real benefit to using RN.ImageBackground.

**Comment by junseld** [comment]
hmm I just installed the new release but have the old `native-common/Image.tsx`.
Any chance something went wrong?

**Comment by erictraut** [comment]
Oops, I didn’t include that change in 1.3.3. I decided it was a bit risky to pull into the stable branch, so I was planning to wait until the next major release (1.4). I normally wait for a few major changes to accumulate, but there haven’t been many lately, so I don’t know when 1.4 will be released. 

How badly do you need this? I can think of several straightforward workarounds.

**Comment by junseld** [comment]
Ah ok ;) thanks.
I kind of did the same thing now in my code so not super badly.
