### ISSUE TITLE
Placeholder property not visible on mobile

### ISSUE THREAD

**Issue by ania-s** [Microsoft/reactxp#771]
We have a TextInput with a defined placeholder property "PLACEHOLDER". However, on mobile side "PLACEHOLDER" is not visible under placeholder but as value. In fact there is no placeholder property at all. And if TextInput has both value and placeholder defined on app side then on mobile side the TextInput has only value property and whatever was defined under placeholder is not visible at all.

**Comment by erictraut** [comment]
I'm not sure I understand what you mean by "not visible under placeholder but as value". Are you saying that the text you provide in the ```placeholder``` prop isn't visible? 

If you specify both a ```placeholder``` and a non-empty ```value``` prop, the text edit box will contain the value, and the placeholder string won't be displayed. This is how placeholders work. They're meant to be visible only when the text edit box is empty. Some platforms also hide the placeholder whenever the text edit box is focused.

**Comment by ania-s** [comment]
I am really sorry for my late reply.
What I mean is that there is nothing like _placeholder_ prop on mobile side. So if I want to see what was specified under _placeholder_ variable in the source code I can check it as long as _value_ was left empty as then _placeholder_ is visible under _value_ prop. Otherwise I cannot access it anyhow.

**Comment by erictraut** [comment]
Sorry, I still don't understand what you mean. What behavior do you expect to see, and what behavior are you seeing instead? Perhaps you can provide a snippet of source code or a screen shot to clarify?

If you specify a placeholder prop to RX.TextInput, ReactXP's implementation simply passes that value through to the underlying RN.TextInput placeholder prop. It doesn't perform any transformation.  See line 97 of [this source file](https://github.com/Microsoft/reactxp/blob/master/src/native-common/TextInput.tsx).

**Comment by erictraut** [comment]
Thanks for the explanation. I now understand.

It appears that the React Native Android implementation removes the placeholder attribute if a non-empty value is present. ReactXP is simply passing the placeholder prop through to the underlying RN.TextInput.

That said, I'm not sure why you care. This is an internal implementation detail that has no impact on the control's behavior or appearance. The placeholder text, by definition, won't ever be visible if there's a non-empty value specified.

My guess is that you are trying to access the placeholder attribute value in some test code to validate that your app's code passed an expected value for the placeholder prop. That approach won't work here because you're relying on an internal implementation details that is not guaranteed by the contract.

**Comment by ania-s** [comment]
Yes this is for the testing and it's not even about what placeholder value is. It's to assure the value we get from a TextField comes from what was typed in by a user and not a placeholder. 
And yes we can make sure in our tests that we never use placeholder value to type into this TextInput but it would be much safer just to assure where the value comes from - placeholder or user input. 
It's a small chance that someone will change a value of placeholder to what we use in our tests to type into the TextInput, but it might still happen and then we might have false positive...
