### ISSUE TITLE
Click/Tap Event, when tapping the RX.TextField

### ISSUE THREAD

**Issue by shameister** [Microsoft/reactxp#777]
We really love ReactXP,

but every so often it seems to come to its limit, where I have no clue, how to solve something, without requesting a new feature.

<img width="565" alt="bildschirmfoto 2018-08-14 um 08 15 07" src="https://user-images.githubusercontent.com/98413/44074777-5856f79e-9f9a-11e8-9485-6dd4bb7ee374.png">

When focussing the RX.TextField our autocomplete-suggestion opens.

It closes
* after selecting a value (by tap or keyboard)
* when pressing escape
* after blur of the RX.TextField

Since nearly every part of the screen is interactive, the option of blurring the field isn't that easy. So we decided, that we also like to hide the autocompletion, when clicking/tapping into the RX.TextField. Since the field already has the focus the onFocus-method is not fired obviously.

This is, when I asked myself, why there is no onClick/onTap-event. I'd expect that these events are very similar on all target platforms.

Did I missed a thing or is this really impossible so far?

Looking forward to your response. :-)

Sascha

**Comment by erictraut** [comment]
Just to clarify, are you looking for a global onClick/onPress event — something that's not related to any component but acts as a "catch all" if it bubbles all the way to the top of the visual hierarchy? That's been requested previously. See [here](https://github.com/Microsoft/reactxp/pull/669). Unfortunately, we haven't been able to come up with a clean way to implement this across the web and native platforms. Some hacks were suggested, but they turn out to be very fragile.

Or are you talking about an onPress prop for the RX.TextInput component? That might be feasible to implement in a cross-platform manner, but I'd want to explore alternative approaches first. We prefer not to add complexity (additional props, interactions, etc.) unless there's a really good reason for them because it makes it more difficult to add new platforms in the future. Have you tried enclosing your RX.TextInput instance with an RX.View instance that has an onPress handler?

**Comment by shameister** [comment]
Hey Eric,

thanks for your response. To clarify: I was asking for an onPress prop on the RX.TextInput component. I tried your suggestion to enclose the TextInput with a View and it seems to work for me.

For me this is kind of counter-intuitive. Maybe it would be good to document this behavior somewhere to reduce future feature requests?
