### ISSUE TITLE
Hardwired @types/react cause conflicts

### ISSUE THREAD

**Issue by pronebird** [Microsoft/reactxp#781]
I am having some issues using Reactxp with TypeScript, a lot of stuff like this pops in my terminal:

```
../../node_modules/reactxp/node_modules/@types/react/index.d.ts:3907:13 - error TS2717: Subsequent property declarations must have the same type.  Property 'metadata' must be of type 'SVGProps<SVGMetadataElement>', but here has type 'SVGProps<SVGMetadataElement>'.

3907             metadata: React.SVGProps<SVGMetadataElement>;
```

I realized that this happens because ReactXP has a hardwired dependency to `@types/react` and that I have more than one installation of the aforementioned `@types/react`. That's what current master lists as deps:

```json
"@types/react": "16.0.36",
"@types/react-dom": "16.0.6",
```

Inspecting `yarn.lock` file revealed that all other dependencies including `react-dom` and `prop-types` reference basically any version or `@types/react` (`*`):

```
"@types/react-dom@16.0.6":
  version "16.0.6"
  resolved "https://registry.yarnpkg.com/@types/react-dom/-/react-dom-16.0.6.tgz#f1a65a4e7be8ed5d123f8b3b9eacc913e35a1a3c"
  dependencies:
    "@types/node" "*"
    "@types/react" "*"
```

and that "any" version resolves to the latest:

```
"@types/react@*":
  version "16.4.11"
  resolved "https://registry.yarnpkg.com/@types/react/-/react-16.4.11.tgz#330f3d864300f71150dc2d125e48644c098f8770"
  dependencies:
    "@types/prop-types" "*"
    csstype "^2.2.0"
```

So when Yarn stumbles upon this it de-dupes both `@types/react` packages:

```
$ cat node_modules/reactxp/node_modules/@types/react/package.json | grep version
    "version": "16.0.36",
$ cat node_modules/@types/react/package.json | grep version 
    "version": "16.4.11",
```

ReactXP also demands the `react@16.4.0` to be installed:

```json
  "peerDependencies": {
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
```

Given all of this I think current `package.json` contains the impossible configuration, where it basically demands newer React but uses much older typings for it. 

Huge blocker to start using Reactxp with TypeScript.

I've tried bumping dependencies in ReactXP, but I am not able to compile RX then, due to bunch of these:

```
src/android/ReactXP.ts:82:16 - error TS2322: Type 'typeof import("/Users/pronebird/Desktop/reactxp/src/native-common/Button").Button' is not assignable to type 'typeof import("/Users/pronebird/Desktop/reactxp/src/common/Interfaces").Button'.

82     export var Button: typeof RXInterfaces.Button = ButtonImpl;
                  ~~~~~~
```

Not sure why. Maybe some underlying React types gained some new props.

**Comment by erictraut** [comment]
First, ReactXP doesn't demand any particular version of react or react-native. Those are listed as "peer dependencies", which allows you to choose a wide range of react and react-native versions within your app.

ReactXP _does_ depend on a particular version of @types/react (and a few other types modules). We tried using semver notation ("^") here in the past, but updates to @types modules regularly introduce breaking changes and have suddenly and unexpectedly left ReactXP in an unbuildable state. 

Npm and yarn shouldn't have a problem managing two versions of the same type library. They are designed to handle this case. Normally it's undesirable to include two versions of the same dependency within your app because it adds both copies to your final package, but in this case we're talking about type files which are used at build time only. 

This looks to be a typescript configuration issue in your project. I'm guessing that you've configured typescript to include all type definition (".d.ts") files, so it's picking up both versions and complaining about the differences it sees. Here are a couple of things you can try. 
1. In your tsconfig, add the option "skipLibCheck": true. 
2. If that doesn't work, add an explicit "types" config parameter that lists the library type files you want it to include, e.g. "types": ["react", "react-dom", "react-native"].

**Comment by pronebird** [comment]
@erictraut thanks 🙏 I wasn’t aware of skipLibCheck and used ‘types’ instead.
