### ISSUE TITLE
RX.Text selectable property doesnt behave as expected

### ISSUE THREAD

**Issue by shameister** [Microsoft/reactxp#829]
Hello,

I am creating an element while panning vertically in a GestureView. This element contains a RX.Text, which has `selectable` set to `false`. When panning so far, that the mouse drags over the RX.Text-position, the text becomes selected. As I set selectable to false, I did not expected this behavior.

![bildschirmfoto 2018-09-27 um 15 53 14](https://user-images.githubusercontent.com/98413/46150817-be04a780-c26d-11e8-8584-0974f9c3588d.png)

Is this a RXP bug or can I solve it myself?

Regards,
Sascha

**Comment by shameister** [comment]
Oh, I am sorry. Again web (Electron 3.0.0)

**Comment by shameister** [comment]
This is the JSX-markup:
`return (<RX.View style={ [ styles.placeholderBaseStyle, dynamicStyle] }>
        <RX.Text style={ styles.durationAndTime } selectable={false}>{ durationString } | {startString} - {endString}</RX.Text>
</RX.View>)`

This is, what is rendered (as the chromium debugger shows):

`<div role="none" style="position: absolute; display: flex; flex-direction: column; flex-grow: 0; flex-shrink: 0; overflow: hidden; align-items: stretch; background-color: rgba(188, 232, 241, 0.3); border-width: 1px; border-style: dashed; border-color: rgb(0, 68, 128); left: 0px; right: 0px; top: 1976px; height: 38px;"><div style="position: relative; display: inline; flex-grow: 0; flex-shrink: 0; overflow: hidden; white-space: pre-wrap; overflow-wrap: break-word; font-size: 10px; padding: 5px; font-weight: bold; text-align: right; cursor: inherit;">00:19 Std. | 16:28 - 16:47</div></div>`

I can't find an attribute in the rendered markup. I'd expect something from [this list](https://css-tricks.com/almanac/properties/u/user-select/).

Regards,
Sacha

**Comment by shameister** [comment]
When adding `['user-select' as string]: 'none'` to the style of the RX.Text, the code behaves like, I expected, when setting selectable to false. Maybe RXP sets another style, which is not supported by chromium?

**Comment by m1ck2** [comment]
To be honest I am not sure what is happening or what the problem is but I think everything should initially set as previous user had it if that was proven to work then any adjustments and improvements can be added one by one from there so if any failure we know where to start. 


Sent from Yahoo Mail for iPhone


On Sunday, September 30, 2018, 4:20 am, Eric Traut <notifications@github.com> wrote:


@mshoho, what are your thoughts on this? You wrote the code in web/Text.tsx that uses the "data-text-as-pseudo-element" pseudo element to prevent selections. I think the previous code used userSelect: 'none'. Would it make sense to also add a userSelect: 'none' in the non-selectable case — in addition to the pseudo element attribute? Or would that break something?

**Comment by mshoho** [comment]
I don't see `data-text-as-pseudo-element` in the generated code, but as I check the code for it:

`if (this.props.selectable || typeof this.props.children !== 'string')`, so it seems like the second condition shoots here (the Text's content is non-trivial). I don't remember the exact reasoning for the second condition but I suppose it was like «make sure it's an actual text which could be put to the data attribute, because who knows what other views and images people can put there».

So, as a workaround you can try to do this: ```<RX.Text style={ styles.durationAndTime } selectable={false}>{ `${durationString} | ${startString} - ${endString}` }</RX.Text>``` (or preconcatenate it any other way).

And perhaps we should address the second part of that if. I was thinking about replacing this `data-text-as-pseudo-element` with handling the `copy` event and choose the actual text to select programmatically from that event handler. It's much more agile from the desired result perspective, though also much more complicated. So, maybe some day.

**Comment by shameister** [comment]
After updating to the newest RX release, this issue does not appear anymore.
