### ISSUE TITLE
i want my react native app to eventually be working on laptop browser using reactXP,   should i start building with react-native  then go to react XP  or vice versa ?

### ISSUE THREAD

**Issue by jpca999** [Microsoft/reactxp#84]
what is better way of building it ?
should i start building with react-native  then go to react XP ?
or should i start with react XP and then back to react-native ?

**Comment by erictraut** [comment]
If you know that you want your app to run on both React Native and web, it would be better to start with ReactXP. If you start with React Native, you will need to revisit all of your code and switch it to ReactXP classes. If you start with ReactXP, React Native and web will both work from the start.

**Comment by jpca999** [comment]
On scale of 1-10 How much of a diffenrece is 

Between react native way of building vs Reactxp ? 

If someone knows RN how much of a learning curve is it ?

**Comment by erictraut** [comment]
The concepts are all the same, so if you're used to React Native (or React JS, for that matter), you'll feel very comfortable using ReactXP. They use the exact same lifecycle methods (componentDidMount, componentWillUnmount, etc.) and the same render methods. The only difference is that instead of specifying RN components when rendering, you specify ReactXP components instead. Most of the components have the same names and share most of the same props. For example, "View", "Text", "TextInput" and "ScrollView" are almost identical. Some components, like ReacXP's Button, differ a bit. RN doesn't have a "Button" component, but instead offers a "TouchableHighlight" which is similar. Likewise, gesture handling is exposed a bit differently. With RN, you use a gesture responder (or a higher-level PanResponder). In ReactXP, these are exposed using a somewhat-easier-to-use "GestureView". Some RN components (like ToolbarAndroid and SnapshotViewIOS) have no ReactXP equivalent because they are platform-specific. You can still use them in your ReactXP app, but you'll need to conditionalize their use because there is no equivalent on the web.
