### ISSUE TITLE
How to read properties from StyleRuleSets?

### ISSUE THREAD

**Issue by shameister** [Microsoft/reactxp#867]
We have an interface, which allows a user to add style to an object.

```
interface CustomImageProps
{
  style?:RX.Types.StyleRuleSet<RX.Types.ImageStyle>|RX.Types.StyleRuleSet<RX.Types.ImageStyle>[]
}
```

Later on, we´d like to read margin/padding from this props, but didn´t find out, how to access these properties. Looking forward for a hint.

Regards,
Sascha

**Comment by erictraut** [comment]
You can't access style components later. They are combined and potentially transformed and even cached (and represented by a number rather than an object). From the perspective of the javascript code, the style prop is an abstract object. 

Why do you need to read the margin/padding values at a later time? Perhaps there's another way to solve the problem.

**Comment by erictraut** [comment]
I see. Yeah, there's really no way to query a child component for its effective margin and padding values. Styles can be specified as nested arrays, which are combined into a single effective style sheet, which is then potentially cached in an abstracted form.

Why not simply enclose the RXImageSvg with an RX.View and allow the dimensions of the RX.View to be defined by the image it's enclosing? I don't see why you'd need to specify its width and height explicitly.

**Comment by shameister** [comment]
This will work. Thanks. :)
