### ISSUE TITLE
RX.View onLongPress on web

### ISSUE THREAD

**Issue by sebleclerc** [microsoft/reactxp#985]
I am working on adding a long press on a RX.View.

I tried my code on iOS and Android, everything is good but the `onLongPress` is never called. I checked the documentation for `RX.View` ( [link](https://microsoft.github.io/reactxp/docs/components/view.html) ), I see the `onLongPress` is touch specific event. Any reason why? Any plan to add this as mouse event too in the near futur?

I checked `RX.GestureView` and `RX.Link` and both have `onLongPress` to be also mouse event. And using a `RX.GestureView` is not an option for me.

Thanks!

**Comment by erictraut** [comment]
Have you considered using RX.Button? That's the class that's really intended to be used for clicks and presses, including long press.

**Comment by sebleclerc** [comment]
I do have considered it but I am embedding views inside others where each of them have `onPress` to do different things. And `RX.Button` couldn't do this.

**Comment by erictraut** [comment]
RX.View wasn't intended to be used for user interactions. It's supposed to be a simple container. RX.Button, RX.Gesture and RX.Link are designed with user interaction in mind. Over time, some event handling has crept into RX.View. In particular, onPress was added because of HTML's limitation on nested buttons, but we've tried to avoid adding more complexity to RX.View. So I'm reluctant to add full onLongPress support here. I had forgotten that we had added partial support for touch-based long press events. Given that we've already added partial support, there's a reasonable argument to be made that we should finish it for the web.

**Comment by dagatsoin** [comment]
@sebleclerc @erictraut 

I relaunch this conversation because IMO I think it highlights a deep separation of concern issue.

> RX.View wasn't intended to be used for user interactions. It's supposed to be a simple container.

I am currently making an UI library with [ReactXP]( https://dagatsoin.github.io/sproutch/) and I encounter some problems with the actual separation of concern (SOC) about the touch events.

On RN, a button is an abstraction of a Touchable with just onPress exposed on it. As the doc say, « A basic button component that should render nicely on any platform. Supports a minimal level of customization. »
It is not intended to be customizable.

On the web, button is also an abstraction with a specific exposed API (disable, form) to be easily use in a form.

Both  implementations are possible to do with their ascendant. A Div for web and a Touchable.

But ReactXP have a different SOC.
The Touchable events (onPressIn, onPressOut, etc.) are splited between a low (View) and a high level (Button) component. (I don’t talk about Gesture and Link here to simplify).

This has two major consequences :
- Some specific event like onPressIn, onPressOut are not exposed on lower element like View making View a not-so-low level component
- Button has limited set of authorized children, so we can’t nest button to achieve complexe layout.

For exemple, if you want your component to do some business thing on different touch phase.
Actually to implement this. I need to make this layout

```
<View onPress={() => doBusinessStuff1()}>
  {this.props.children}
  <Button
    style={this.absoluteStyleToCoverTheArea} // :(
    onPressIn={() => doBusinessStuff2()} // SOC issue
    onPressOut={() => doBusinessStuff3()} // SOC issue
  />
</View>
```
```
<View
  onPress={() => doBusinessStuff1()}
  onPressIn={() => doBusinessStuff2()} // Ok here
  onPressOut={() => doBusinessStuff3()} // Ok here
>
  {this.props.children}
</View>
```

This general example may be applied to complexe UI component like a draggable list, a button with ripple effect, but also with smart component with data fetching logic, which would lead to inconsistant code.

So my suggestion is that the View component expose all the atomic `RN.Touchable` events so that it will become a real powerful, low level, basic component.

**Comment by erictraut** [comment]
RX.View is not meant to be a superset of all other components in ReactXP.

There are a number of behaviors of RX.Button that cannot be implemented with an RX.View — including the proper accessibility behaviors associated with a button. The onPressIn/onPressOut callbacks are another example. So is onHoverStart/onHoverEnd.

If you need to do something that is relatively non-standard (outside of what the vast majority of apps require), you have the ability to write a ReactXP extension and leverage any of the platform-specific low-level components and APIs. I'm not sure what you're trying to do, but that's one option.

If there is a specific behavior that you want to add to RX.View that you think would be generally valuable to many apps, let's talk about those specific behaviors. In general, the bar is high for adding new functionality to RX.View because it is already overly complex IMO. Part of this was because ReactXP was developed somewhat organically in its early phases, and functionality was added to RX.View without enough thought. Part of this is because of the unfortunate HTML limitation that prevents a button from being nested inside of another button, which led us to expose some button-like behaviors from RX.View.

**Comment by dagatsoin** [comment]
I understand the concern. You intent to get the same level of responsability to View as in RN.
After a second read of the docs, I see that Button can also take children. Making it the candidate to the Touchable equivalent.
On the other hand the naming could be confusing thought.
