### ISSUE TITLE
Support for Sockets (Vert.x3 / SockJS-based event bus bridge)

### ISSUE THREAD

**Issue by lsimonebshop** [Microsoft/reactxp#986]
Hi,
I'm trying to get data from the server listening to EventBus (SockJS-based event bus bridge to connect a JavaScript frontend application to Vertx), but I ended up being successfull only on Android Platform.
In windows I can only see a single entry on Network Inspector:
GET XHR /info?t=1547478652706       [Having no result]
From a different point of view which isn't related to socket transactions, using Fetch from Networking Docs of React Native for dispatching requests to a REST API has faults in Windows Platforms.
Is it somehow related to not using REST Client which handles retry logic, authentication and setting of HTTP header values?
Is there a way to manage socket transactions maintaining a multi-platform environment(Android,iOS,UWP)?

JS Code
` var eb = new EventBus("http://localhost:8080/eventbus");
		console.log(eb)
		
		eb.onopen = function () {
            //It never gets here
            console.log("Socket open!");   
        }
		
        return () => {
           console.log("Socket off")
       }`

**Comment by berickson1** [comment]
Based on the past issues in SockJS backlog, version 1.1.5 and higher should support ReactNative based environments. For networking, you're directly using the ReactNative/browser implementation of websockets/fetch/xhr, ReactXP doesn't do anything to these apis (and in our experience, the implementations have been pretty similar across platforms). I believe this issue is more suited to be opened against React Native itself.

The REST Client examples that are provided (via SimpleRestClients) in ReactXP docs are simply an additional abstraction on XHR to make network requests promise-based (plus a few other features).
