### ISSUE TITLE
VirtualListView - initialSelectedKey Prop

### ISSUE THREAD

**Issue by alariej** [Microsoft/reactxp#987]
I am trying to use the VirtualListView component to display a chat conversation. The idea would be to load that component with the most recent message (at the bottom of the conversation) in its visible area. I was hoping that the initialSelectedKey property would force the component to bring whatever item identified by that key value into focus and in the visible area. But unfortunately the component always initially displays the top of the list, irrespective of what I set in initialSelectedKey. I noted that the initialSelectedKey value is reflected correctly in the VirtualListViewCellRenderDetails item identified by the key (its isFocused property turns to true), but nothing happens visually.

Do I understand initialSelectedKey correctly? Is this the correct property to use for setting the initial part of the list to be displayed?

**Comment by deregtd** [comment]
Partially.  It's to denote which item is selected, which is for accessibility/keyboard focusing.  One could make the argument that if the initialselectedkey is off screen, that the VLV should attempt to scroll to it, though.  I'll wait for @berickson1 to respond in case I'm off base here.

In the meantime, you definitely need to manually scroll to the item that you want to jump to.

**Comment by berickson1** [comment]
I agree with @alariej - we should scroll when initialSelectedKey is set. I just raised #989 to address this

**Comment by berickson1** [comment]
Just published reactxp-virtuallistview@2.0.0-rc.2. @alariej - give it a shot

**Comment by alariej** [comment]
Thanks for looking at this issue so quickly. I installed VLV rc.2 and just tested it:
1) I do not get any scroll at all by setting initialSelectedKey to the key value of the item at the bottom of the list. The VLV stays at the top on loading.
2) I now get some initial scrolling when using the selectItemKey method on the onLayout event, but it scrolls only about half-way to the bottom. To be precise, it scrolls by 372 pixels on a VLV with _containerHeight of 799.
Might it be that the final _containerHeight is not known at mounting time (or event at the onLayout event), so that the scrolling takes place, but with wrong values?

**Comment by berickson1** [comment]
Are you using fixed size components in VLV? Most of  the extended functionality of VLV assumes that components are fixed size.  Dynamic components needs to be measured before we can perform operations relating to their sizes. Something like scrollTo on a large VLV with only dynamic items can be hugely expensive since all items above the scrollTo key would need to be rendered first.
It sounds like you're possibly bumping up against some of the limitations of VLV and might need a more specialized component

**Comment by erictraut** [comment]
Yeah, the VLV is not well suited for a bottoms-up chat view. The Skype team implemented a completely different customized view for chat messages because VLV was insufficient for this purpose. If you've looked at the VLV implementation, you'll notice that it uses a component called the VirtualListCell. That component should be a good starting point for a specialized "VirtualMessageView".

**Comment by alariej** [comment]
Indeed, I am using measureHeight when building the itemList. I unfortunately can't use a fixed item height, as I use the component to display a chat conversation. So far I thought the VLV suits quite well for that purpose, as it only renders the new message which adds up to the conversation, and allows various styles for the individual items. The only thing missing really is a single scroll parameter which tells the component to display either the top, or the bottom.

**Comment by erictraut** [comment]
The interaction between rendering and scrolling is not well defined and is inconsistent between platforms. On Android, everything is very async, taking place on different threads. On web, it's mostly synchronous, so I'm surprised to hear it doesn't work there. In any case, making this work in a cross-platform manner is going to be very challenging. I say that from experience. In Skype, we needed to write our own custom native components on Android because the built-in ScrollView provided no way to synchronize between scrolling and rendering.
